// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#define MAP_SIZE 4096UL
#define MAP_MASK (MAP_SIZE - 1)

/***************************** Include Files *********************************/
#include "xhwfreqscale_simple_adder.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XHwfreqscale_simple_adder_CfgInitialize(XHwfreqscale_simple_adder *InstancePtr, XHwfreqscale_simple_adder_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

XHwfreqscale_simple_adder setup_XHwfreqscale_simple_adder() //returns a pointer in userspace to the device
{
    void *mapped_base_hwfreqscale;
    int memfd_hwfreqscale;

    void *mapped_dev_base;
    off_t dev_base = HWFREQSCALE_ADDR;

    memfd_hwfreqscale = open("/dev/mem", O_RDWR | O_SYNC); //to open this the program needs to be run as root
        if (memfd_hwfreqscale == -1) {
        printf("Can't open /dev/mem.\n");
        exit(0);
    }
    //printf("/dev/mem opened.\n"); 

    // Map one page of memory into user space such that the device is in that page, but it may not
    // be at the start of the page.

    mapped_base_hwfreqscale = mmap(0, MAP_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, memfd_hwfreqscale, dev_base & ~MAP_MASK);
        if (mapped_base_hwfreqscale == (void *) -1) {
        printf("Can't map the memory to user space.\n");
        exit(0);
    }
     //printf("Memory mapped at address %p.\n", mapped_base_hhbquery); 

    // get the address of the device in user space which will be an offset from the base 
    // that was mapped as memory is mapped at the start of a page 

    mapped_dev_base = mapped_base_hwfreqscale + (dev_base & MAP_MASK);
    XHwfreqscale_simple_adder device;
    device.Bus_a_BaseAddress = mapped_dev_base;
    device.IsReady = 1;

    return device;
    //return mapped_dev_base;
}



void XHwfreqscale_simple_adder_Start(XHwfreqscale_simple_adder *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_AP_CTRL) & 0x80;
    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XHwfreqscale_simple_adder_IsDone(XHwfreqscale_simple_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XHwfreqscale_simple_adder_IsIdle(XHwfreqscale_simple_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XHwfreqscale_simple_adder_IsReady(XHwfreqscale_simple_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XHwfreqscale_simple_adder_EnableAutoRestart(XHwfreqscale_simple_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XHwfreqscale_simple_adder_DisableAutoRestart(XHwfreqscale_simple_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_AP_CTRL, 0);
}

void XHwfreqscale_simple_adder_SetInput1(XHwfreqscale_simple_adder *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_INPUT1_DATA, Data);
}

u32 XHwfreqscale_simple_adder_GetInput1(XHwfreqscale_simple_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_INPUT1_DATA);
    return Data;
}

void XHwfreqscale_simple_adder_SetInput2(XHwfreqscale_simple_adder *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_INPUT2_DATA, Data);
}

u32 XHwfreqscale_simple_adder_GetInput2(XHwfreqscale_simple_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_INPUT2_DATA);
    return Data;
}

u32 XHwfreqscale_simple_adder_GetOutput_r(XHwfreqscale_simple_adder *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_OUTPUT_R_DATA);
    return Data;
}

void XHwfreqscale_simple_adder_InterruptGlobalEnable(XHwfreqscale_simple_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_GIE, 1);
}

void XHwfreqscale_simple_adder_InterruptGlobalDisable(XHwfreqscale_simple_adder *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_GIE, 0);
}

void XHwfreqscale_simple_adder_InterruptEnable(XHwfreqscale_simple_adder *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_IER);
    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_IER, Register | Mask);
}

void XHwfreqscale_simple_adder_InterruptDisable(XHwfreqscale_simple_adder *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_IER);
    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_IER, Register & (~Mask));
}

void XHwfreqscale_simple_adder_InterruptClear(XHwfreqscale_simple_adder *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XHwfreqscale_simple_adder_WriteReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_ISR, Mask);
}

u32 XHwfreqscale_simple_adder_InterruptGetEnabled(XHwfreqscale_simple_adder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_IER);
}

u32 XHwfreqscale_simple_adder_InterruptGetStatus(XHwfreqscale_simple_adder *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XHwfreqscale_simple_adder_ReadReg(InstancePtr->Bus_a_BaseAddress, XHWFREQSCALE_SIMPLE_ADDER_BUS_A_ADDR_ISR);
}

