// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="combiner_top,hls_ip_2013_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0}" *)

module combiner_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_points_in_req_din,
        data_points_in_req_full_n,
        data_points_in_req_write,
        data_points_in_rsp_empty_n,
        data_points_in_rsp_read,
        data_points_in_address,
        data_points_in_datain,
        data_points_in_dataout,
        data_points_in_size,
        kernel_info_in_req_din,
        kernel_info_in_req_full_n,
        kernel_info_in_req_write,
        kernel_info_in_rsp_empty_n,
        kernel_info_in_rsp_read,
        kernel_info_in_address,
        kernel_info_in_datain,
        kernel_info_in_dataout,
        kernel_info_in_size,
        centres_out_req_din,
        centres_out_req_full_n,
        centres_out_req_write,
        centres_out_rsp_empty_n,
        centres_out_rsp_read,
        centres_out_address,
        centres_out_datain,
        centres_out_dataout,
        centres_out_size,
        distortion_out,
        distortion_out_ap_vld,
        n,
        k_V
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   data_points_in_req_din;
input   data_points_in_req_full_n;
output   data_points_in_req_write;
input   data_points_in_rsp_empty_n;
output   data_points_in_rsp_read;
output  [31:0] data_points_in_address;
input  [31:0] data_points_in_datain;
output  [31:0] data_points_in_dataout;
output  [31:0] data_points_in_size;
output   kernel_info_in_req_din;
input   kernel_info_in_req_full_n;
output   kernel_info_in_req_write;
input   kernel_info_in_rsp_empty_n;
output   kernel_info_in_rsp_read;
output  [31:0] kernel_info_in_address;
input  [31:0] kernel_info_in_datain;
output  [31:0] kernel_info_in_dataout;
output  [31:0] kernel_info_in_size;
output   centres_out_req_din;
input   centres_out_req_full_n;
output   centres_out_req_write;
input   centres_out_rsp_empty_n;
output   centres_out_rsp_read;
output  [31:0] centres_out_address;
input  [31:0] centres_out_datain;
output  [31:0] centres_out_dataout;
output  [31:0] centres_out_size;
output  [31:0] distortion_out;
output   distortion_out_ap_vld;
input  [31:0] n;
input  [7:0] k_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_points_in_req_write;
reg data_points_in_rsp_read;
reg kernel_info_in_req_write;
reg kernel_info_in_rsp_read;
reg centres_out_req_din;
reg centres_out_req_write;
reg distortion_out_ap_vld;
reg   [3:0] ap_CS_fsm = 4'b0000;
reg   [3:0] indvar_reg_512;
reg   [3:0] ap_reg_ppstg_indvar_reg_512_pp1_it1;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
reg    ap_reg_ppiten_pp1_it2 = 1'b0;
reg    ap_reg_ppiten_pp1_it3 = 1'b0;
reg    ap_reg_ppiten_pp1_it4 = 1'b0;
reg    ap_reg_ppiten_pp1_it5 = 1'b0;
reg   [0:0] exitcond_reg_1077;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1077_pp1_it5;
reg    ap_sig_bdd_97;
reg    ap_reg_ppiten_pp1_it6 = 1'b0;
reg    ap_reg_ppiten_pp1_it7 = 1'b0;
reg   [3:0] ap_reg_ppstg_indvar_reg_512_pp1_it2;
reg   [3:0] ap_reg_ppstg_indvar_reg_512_pp1_it3;
reg   [3:0] ap_reg_ppstg_indvar_reg_512_pp1_it4;
reg   [3:0] ap_reg_ppstg_indvar_reg_512_pp1_it5;
reg   [3:0] ap_reg_ppstg_indvar_reg_512_pp1_it6;
reg   [3:0] indvar2_reg_524;
reg   [3:0] ap_reg_ppstg_indvar2_reg_524_pp2_it1;
reg    ap_reg_ppiten_pp2_it0 = 1'b0;
reg    ap_reg_ppiten_pp2_it1 = 1'b0;
reg    ap_reg_ppiten_pp2_it2 = 1'b0;
reg    ap_reg_ppiten_pp2_it3 = 1'b0;
reg    ap_reg_ppiten_pp2_it4 = 1'b0;
reg    ap_reg_ppiten_pp2_it5 = 1'b0;
reg   [0:0] exitcond2_reg_1106;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_1106_pp2_it5;
reg    ap_sig_bdd_131;
reg    ap_reg_ppiten_pp2_it6 = 1'b0;
reg    ap_reg_ppiten_pp2_it7 = 1'b0;
reg   [3:0] ap_reg_ppstg_indvar2_reg_524_pp2_it2;
reg   [3:0] ap_reg_ppstg_indvar2_reg_524_pp2_it3;
reg   [3:0] ap_reg_ppstg_indvar2_reg_524_pp2_it4;
reg   [3:0] ap_reg_ppstg_indvar2_reg_524_pp2_it5;
reg   [3:0] ap_reg_ppstg_indvar2_reg_524_pp2_it6;
reg   [31:0] total_distortion_reg_547;
reg   [8:0] i5_reg_560;
reg   [29:0] indvar1_reg_571;
wire   [31:0] centre_buffer_2_wgtCent_value_q0;
reg   [31:0] reg_583;
reg   [0:0] exitcond7_reg_1124;
reg    ap_reg_ppiten_pp4_it0 = 1'b0;
reg    ap_reg_ppiten_pp4_it1 = 1'b0;
reg    ap_reg_ppiten_pp4_it2 = 1'b0;
reg    ap_reg_ppiten_pp4_it3 = 1'b0;
reg    ap_reg_ppiten_pp4_it4 = 1'b0;
reg    ap_reg_ppiten_pp4_it5 = 1'b0;
reg    ap_reg_ppiten_pp4_it6 = 1'b0;
reg    ap_reg_ppiten_pp4_it7 = 1'b0;
reg    ap_reg_ppiten_pp4_it8 = 1'b0;
reg    ap_reg_ppiten_pp4_it9 = 1'b0;
reg    ap_reg_ppiten_pp4_it10 = 1'b0;
reg    ap_reg_ppiten_pp4_it11 = 1'b0;
reg    ap_reg_ppiten_pp4_it12 = 1'b0;
reg    ap_reg_ppiten_pp4_it13 = 1'b0;
reg    ap_reg_ppiten_pp4_it14 = 1'b0;
reg    ap_reg_ppiten_pp4_it15 = 1'b0;
reg    ap_reg_ppiten_pp4_it16 = 1'b0;
reg    ap_reg_ppiten_pp4_it17 = 1'b0;
reg    ap_reg_ppiten_pp4_it18 = 1'b0;
reg   [0:0] tmp_s_reg_1203;
wire   [8:0] i_1_fu_593_p2;
wire   [31:0] lim_fu_608_p2;
reg   [31:0] lim_reg_1058;
reg   [31:0] data_points_in_addr_reg_1066;
wire   [0:0] tmp_3_fu_613_p2;
wire   [8:0] tmp_9_cast_cast_fu_628_p1;
reg   [8:0] tmp_9_cast_cast_reg_1072;
wire   [0:0] exitcond_fu_631_p2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1077_pp1_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1077_pp1_it2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1077_pp1_it3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1077_pp1_it4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_1077_pp1_it6;
wire   [3:0] indvar_next_fu_637_p2;
reg   [3:0] indvar_next_reg_1081;
wire   [0:0] isIter0_fu_643_p2;
reg   [0:0] isIter0_reg_1086;
reg   [31:0] data_points_in_addr_read_reg_1090;
wire   [31:0] b2_1_fu_654_p2;
reg   [31:0] b2_1_reg_1095;
reg   [31:0] kernel_info_in_addr_reg_1100;
wire   [0:0] exitcond2_fu_670_p2;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_1106_pp2_it1;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_1106_pp2_it2;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_1106_pp2_it3;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_1106_pp2_it4;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_1106_pp2_it6;
wire   [3:0] indvar_next2_fu_676_p2;
reg   [3:0] indvar_next2_reg_1110;
wire   [0:0] isIter1_fu_682_p2;
reg   [0:0] isIter1_reg_1115;
reg   [31:0] kernel_info_in_addr_read_reg_1119;
wire   [0:0] exitcond7_fu_693_p2;
wire   [2:0] i_3_fu_699_p2;
reg   [2:0] i_3_reg_1128;
wire   [1:0] tmp_21_fu_709_p1;
reg   [1:0] tmp_21_reg_1133;
wire   [4:0] tmp_20_fu_736_p2;
reg   [4:0] tmp_20_reg_1143;
wire   [63:0] tmp_24_fu_799_p1;
reg   [63:0] tmp_24_reg_1183;
reg   [7:0] centre_buffer_count_addr_2_reg_1188;
reg   [7:0] centre_buffer_sum_sq_addr_2_reg_1193;
wire   [31:0] b_1_fu_842_p2;
wire   [0:0] tmp_s_fu_848_p2;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it1;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it2;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it3;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it4;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it5;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it6;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it7;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it8;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it9;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it10;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it11;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it12;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it13;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it14;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it15;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it16;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it17;
reg   [0:0] ap_reg_ppstg_tmp_s_reg_1203_pp4_it18;
wire   [8:0] i_2_fu_853_p2;
reg   [8:0] i_2_reg_1207;
wire   [63:0] tmp_6_fu_863_p1;
reg   [63:0] tmp_6_reg_1212;
wire   [11:0] tmp_10_fu_880_p2;
reg   [11:0] tmp_10_reg_1225;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it1;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it2;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it3;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it4;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it5;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it6;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it7;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it8;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it9;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it10;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it11;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it12;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it13;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it14;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it15;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it16;
reg   [11:0] ap_reg_ppstg_tmp_10_reg_1225_pp4_it17;
wire   [31:0] centre_buffer_count_q0;
reg   [31:0] centre_buffer_count_load_reg_1236;
wire   [31:0] centre_buffer_0_wgtCent_value_q0;
wire   [31:0] p_s_fu_891_p3;
reg   [31:0] p_s_reg_1262;
wire   [31:0] centre_buffer_1_wgtCent_value_q0;
wire   [31:0] total_distortion_1_fu_912_p2;
reg   [31:0] total_distortion_1_reg_1274;
wire   [12:0] tmp_14_cast4_fu_924_p1;
reg   [12:0] tmp_14_cast4_reg_1279;
wire   [29:0] tmp_14_add_i32_shr_fu_1008_p1;
reg   [29:0] tmp_14_add_i32_shr_reg_1284;
wire   [31:0] tmp_14_add_i32_shr_cast_fu_1012_p1;
reg   [31:0] tmp_14_add_i32_shr_cast_reg_1289;
wire   [0:0] exitcond1_fu_1016_p2;
reg   [0:0] exitcond1_reg_1294;
reg    ap_reg_ppiten_pp5_it0 = 1'b0;
reg    ap_reg_ppiten_pp5_it1 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond1_reg_1294_pp5_it1;
reg    ap_sig_bdd_475;
reg    ap_reg_ppiten_pp5_it2 = 1'b0;
wire   [29:0] indvar_next1_fu_1021_p2;
wire   [0:0] isIter_fu_1032_p2;
reg   [0:0] isIter_reg_1308;
reg   [0:0] ap_reg_ppstg_isIter_reg_1308_pp5_it1;
wire   [31:0] c_buffer_q1;
reg   [31:0] c_buffer_load_reg_1312;
reg   [7:0] centre_buffer_0_wgtCent_value_address0;
reg    centre_buffer_0_wgtCent_value_ce0;
reg    centre_buffer_0_wgtCent_value_we0;
reg   [31:0] centre_buffer_0_wgtCent_value_d0;
reg   [7:0] centre_buffer_1_wgtCent_value_address0;
reg    centre_buffer_1_wgtCent_value_ce0;
reg    centre_buffer_1_wgtCent_value_we0;
reg   [31:0] centre_buffer_1_wgtCent_value_d0;
reg   [7:0] centre_buffer_2_wgtCent_value_address0;
reg    centre_buffer_2_wgtCent_value_ce0;
reg    centre_buffer_2_wgtCent_value_we0;
reg   [31:0] centre_buffer_2_wgtCent_value_d0;
reg   [7:0] centre_buffer_sum_sq_address0;
reg    centre_buffer_sum_sq_ce0;
reg    centre_buffer_sum_sq_we0;
reg   [31:0] centre_buffer_sum_sq_d0;
wire   [31:0] centre_buffer_sum_sq_q0;
reg   [7:0] centre_buffer_count_address0;
reg    centre_buffer_count_ce0;
reg    centre_buffer_count_we0;
reg   [31:0] centre_buffer_count_d0;
reg   [2:0] i_buffer_address0;
reg    i_buffer_ce0;
reg    i_buffer_we0;
wire   [31:0] i_buffer_d0;
wire   [31:0] i_buffer_q0;
reg   [3:0] p_buffer_address0;
reg    p_buffer_ce0;
reg    p_buffer_we0;
wire   [31:0] p_buffer_d0;
wire   [31:0] p_buffer_q0;
reg   [3:0] p_buffer_address1;
reg    p_buffer_ce1;
wire   [31:0] p_buffer_q1;
reg   [9:0] c_buffer_address0;
reg    c_buffer_ce0;
reg    c_buffer_we0;
reg   [31:0] c_buffer_d0;
reg   [9:0] c_buffer_address1;
reg    c_buffer_ce1;
reg    c_buffer_we1;
wire   [31:0] c_buffer_d1;
reg   [8:0] i_reg_477;
wire   [0:0] exitcond9_fu_587_p2;
reg   [31:0] b2_reg_488;
reg   [31:0] b_reg_500;
reg   [3:0] indvar_phi_fu_516_p4;
reg   [3:0] indvar2_phi_fu_528_p4;
reg   [2:0] i1_reg_536;
reg   [31:0] total_distortion_phi_fu_552_p4;
reg   [8:0] i5_phi_fu_564_p4;
wire   [63:0] tmp_2_fu_599_p1;
wire   [63:0] tmp_14_fu_649_p1;
wire   [63:0] tmp_29_fu_688_p1;
wire   [63:0] tmp_17_fu_719_p1;
wire   [63:0] tmp_23_fu_746_p1;
wire   [63:0] tmp_29_1_fu_761_p1;
wire   [63:0] tmp_25_fu_766_p1;
wire   [63:0] tmp_19_fu_780_p1;
wire   [63:0] tmp_29_2_fu_794_p1;
wire   [63:0] tmp_13_fu_930_p1;
wire   [63:0] tmp_25_1_fu_945_p1;
wire   [63:0] tmp_25_2_fu_959_p1;
wire   [63:0] tmp_15_fu_1027_p1;
wire   [63:0] tmp_4_fu_618_p1;
wire   [63:0] tmp_7_fu_660_p1;
wire   [31:0] tmp_26_fu_821_p2;
wire   [31:0] tmp_27_fu_828_p2;
wire   [31:0] tmp_28_fu_807_p2;
wire   [31:0] tmp_35_1_fu_814_p2;
wire   [31:0] tmp_35_2_fu_835_p2;
wire   [31:0] grp_fu_898_p2;
wire   [31:0] grp_fu_918_p2;
wire   [31:0] grp_fu_905_p2;
wire   [2:0] tmp_22_fu_713_p2;
wire   [3:0] p_shl_fu_724_p3;
wire   [4:0] p_shl_cast_fu_732_p1;
wire   [4:0] i1_cast8_fu_705_p1;
wire   [31:0] tmp_23_fu_746_p0;
wire   [4:0] tmp_28_1_fu_751_p2;
wire   [31:0] tmp_29_1_fu_761_p0;
wire   [2:0] tmp_18_fu_773_p3;
wire   [4:0] tmp_28_2_fu_785_p2;
wire   [31:0] tmp_29_2_fu_794_p0;
wire   [10:0] p_shl1_fu_868_p3;
wire   [11:0] p_shl1_cast_fu_876_p1;
wire   [11:0] i5_cast6_fu_859_p1;
wire   [0:0] tmp_11_fu_886_p2;
wire   [31:0] grp_fu_898_p0;
wire   [31:0] grp_fu_898_p1;
wire   [31:0] grp_fu_905_p0;
wire   [31:0] grp_fu_905_p1;
wire   [31:0] grp_fu_918_p0;
wire   [31:0] grp_fu_918_p1;
wire   [31:0] tmp_13_fu_930_p0;
wire   [12:0] tmp_24_1_fu_935_p0;
wire   [12:0] tmp_24_1_fu_935_p2;
wire   [31:0] tmp_25_1_fu_945_p0;
wire   [12:0] tmp_24_2_fu_950_p2;
wire   [31:0] tmp_25_2_fu_959_p0;
wire   [11:0] p_shl2_fu_964_p3;
wire   [9:0] p_shl3_fu_975_p3;
wire   [12:0] p_shl2_cast_fu_971_p1;
wire   [12:0] p_shl3_cast_fu_982_p1;
wire   [12:0] tmp_5_fu_986_p2;
wire   [12:0] tmp_14_add_i_fu_992_p2;
wire   [10:0] tmp_9_fu_998_p4;
wire   [29:0] tmp_14_add_i32_shr_cast_fu_1012_p0;
wire    grp_fu_898_ce;
wire    grp_fu_905_ce;
wire    grp_fu_918_ce;
reg   [3:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 4'b0000;
parameter    ap_ST_st2_fsm_1 = 4'b1;
parameter    ap_ST_st3_fsm_2 = 4'b10;
parameter    ap_ST_st4_fsm_3 = 4'b11;
parameter    ap_ST_pp1_stg0_fsm_4 = 4'b100;
parameter    ap_ST_st13_fsm_5 = 4'b101;
parameter    ap_ST_pp2_stg0_fsm_6 = 4'b110;
parameter    ap_ST_st22_fsm_7 = 4'b111;
parameter    ap_ST_st23_fsm_8 = 4'b1000;
parameter    ap_ST_st24_fsm_9 = 4'b1001;
parameter    ap_ST_st25_fsm_10 = 4'b1010;
parameter    ap_ST_pp4_stg0_fsm_11 = 4'b1011;
parameter    ap_ST_pp4_stg1_fsm_12 = 4'b1100;
parameter    ap_ST_st64_fsm_13 = 4'b1101;
parameter    ap_ST_pp5_stg0_fsm_14 = 4'b1110;
parameter    ap_ST_st68_fsm_15 = 4'b1111;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv30_0 = 30'b000000000000000000000000000000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv9_100 = 9'b100000000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv4_C = 4'b1100;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv5_2 = 5'b10;
parameter    ap_const_lv13_1 = 13'b1;
parameter    ap_const_lv13_2 = 13'b10;
parameter    ap_const_lv13_F = 13'b1111;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv30_1 = 30'b1;
parameter    ap_true = 1'b1;


combiner_top_centre_buffer_0_wgtCent_value #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
centre_buffer_0_wgtCent_value_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( centre_buffer_0_wgtCent_value_address0 ),
    .ce0( centre_buffer_0_wgtCent_value_ce0 ),
    .we0( centre_buffer_0_wgtCent_value_we0 ),
    .d0( centre_buffer_0_wgtCent_value_d0 ),
    .q0( centre_buffer_0_wgtCent_value_q0 )
);

combiner_top_centre_buffer_0_wgtCent_value #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
centre_buffer_1_wgtCent_value_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( centre_buffer_1_wgtCent_value_address0 ),
    .ce0( centre_buffer_1_wgtCent_value_ce0 ),
    .we0( centre_buffer_1_wgtCent_value_we0 ),
    .d0( centre_buffer_1_wgtCent_value_d0 ),
    .q0( centre_buffer_1_wgtCent_value_q0 )
);

combiner_top_centre_buffer_0_wgtCent_value #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
centre_buffer_2_wgtCent_value_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( centre_buffer_2_wgtCent_value_address0 ),
    .ce0( centre_buffer_2_wgtCent_value_ce0 ),
    .we0( centre_buffer_2_wgtCent_value_we0 ),
    .d0( centre_buffer_2_wgtCent_value_d0 ),
    .q0( centre_buffer_2_wgtCent_value_q0 )
);

combiner_top_centre_buffer_0_wgtCent_value #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
centre_buffer_sum_sq_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( centre_buffer_sum_sq_address0 ),
    .ce0( centre_buffer_sum_sq_ce0 ),
    .we0( centre_buffer_sum_sq_we0 ),
    .d0( centre_buffer_sum_sq_d0 ),
    .q0( centre_buffer_sum_sq_q0 )
);

combiner_top_centre_buffer_0_wgtCent_value #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
centre_buffer_count_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( centre_buffer_count_address0 ),
    .ce0( centre_buffer_count_ce0 ),
    .we0( centre_buffer_count_we0 ),
    .d0( centre_buffer_count_d0 ),
    .q0( centre_buffer_count_q0 )
);

combiner_top_i_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
i_buffer_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( i_buffer_address0 ),
    .ce0( i_buffer_ce0 ),
    .we0( i_buffer_we0 ),
    .d0( i_buffer_d0 ),
    .q0( i_buffer_q0 )
);

combiner_top_p_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 12 ),
    .AddressWidth( 4 ))
p_buffer_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( p_buffer_address0 ),
    .ce0( p_buffer_ce0 ),
    .we0( p_buffer_we0 ),
    .d0( p_buffer_d0 ),
    .q0( p_buffer_q0 ),
    .address1( p_buffer_address1 ),
    .ce1( p_buffer_ce1 ),
    .q1( p_buffer_q1 )
);

combiner_top_c_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 768 ),
    .AddressWidth( 10 ))
c_buffer_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( c_buffer_address0 ),
    .ce0( c_buffer_ce0 ),
    .we0( c_buffer_we0 ),
    .d0( c_buffer_d0 ),
    .address1( c_buffer_address1 ),
    .ce1( c_buffer_ce1 ),
    .we1( c_buffer_we1 ),
    .d1( c_buffer_d1 ),
    .q1( c_buffer_q1 )
);

combiner_top_udiv_32ns_32ns_32_35 #(
    .ID( 1 ),
    .NUM_STAGE( 35 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
combiner_top_udiv_32ns_32ns_32_35_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_898_p0 ),
    .din1( grp_fu_898_p1 ),
    .ce( grp_fu_898_ce ),
    .dout( grp_fu_898_p2 )
);

combiner_top_udiv_32ns_32ns_32_35 #(
    .ID( 2 ),
    .NUM_STAGE( 35 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
combiner_top_udiv_32ns_32ns_32_35_U2(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_905_p0 ),
    .din1( grp_fu_905_p1 ),
    .ce( grp_fu_905_ce ),
    .dout( grp_fu_905_p2 )
);

combiner_top_udiv_32ns_32ns_32_35 #(
    .ID( 3 ),
    .NUM_STAGE( 35 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
combiner_top_udiv_32ns_32ns_32_35_U3(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_918_p0 ),
    .din1( grp_fu_918_p1 ),
    .ce( grp_fu_918_ce ),
    .dout( grp_fu_918_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & ~(ap_const_lv1_0 == exitcond_fu_631_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & (ap_const_lv1_0 == exitcond_fu_631_p2))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_3_fu_613_p2)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & ~(ap_const_lv1_0 == exitcond_fu_631_p2)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
            ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
        end
    end
end

/// ap_reg_ppiten_pp1_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
            ap_reg_ppiten_pp1_it3 <= ap_reg_ppiten_pp1_it2;
        end
    end
end

/// ap_reg_ppiten_pp1_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
            ap_reg_ppiten_pp1_it4 <= ap_reg_ppiten_pp1_it3;
        end
    end
end

/// ap_reg_ppiten_pp1_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it5 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
            ap_reg_ppiten_pp1_it5 <= ap_reg_ppiten_pp1_it4;
        end
    end
end

/// ap_reg_ppiten_pp1_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it6 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
            ap_reg_ppiten_pp1_it6 <= ap_reg_ppiten_pp1_it5;
        end
    end
end

/// ap_reg_ppiten_pp1_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it7 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
            ap_reg_ppiten_pp1_it7 <= ap_reg_ppiten_pp1_it6;
        end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
            ap_reg_ppiten_pp1_it7 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp2_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~(ap_const_lv1_0 == exitcond2_fu_670_p2))) begin
            ap_reg_ppiten_pp2_it0 <= ap_const_logic_0;
        end else if ((ap_ST_st13_fsm_5 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp2_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp2_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & (ap_const_lv1_0 == exitcond2_fu_670_p2))) begin
            ap_reg_ppiten_pp2_it1 <= ap_const_logic_1;
        end else if (((ap_ST_st13_fsm_5 == ap_CS_fsm) | ((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~(ap_const_lv1_0 == exitcond2_fu_670_p2)))) begin
            ap_reg_ppiten_pp2_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp2_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
            ap_reg_ppiten_pp2_it2 <= ap_reg_ppiten_pp2_it1;
        end
    end
end

/// ap_reg_ppiten_pp2_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it3 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
            ap_reg_ppiten_pp2_it3 <= ap_reg_ppiten_pp2_it2;
        end
    end
end

/// ap_reg_ppiten_pp2_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it4 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
            ap_reg_ppiten_pp2_it4 <= ap_reg_ppiten_pp2_it3;
        end
    end
end

/// ap_reg_ppiten_pp2_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it5 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
            ap_reg_ppiten_pp2_it5 <= ap_reg_ppiten_pp2_it4;
        end
    end
end

/// ap_reg_ppiten_pp2_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it6 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
            ap_reg_ppiten_pp2_it6 <= ap_reg_ppiten_pp2_it5;
        end
    end
end

/// ap_reg_ppiten_pp2_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp2_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp2_it7 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
            ap_reg_ppiten_pp2_it7 <= ap_reg_ppiten_pp2_it6;
        end else if ((ap_ST_st13_fsm_5 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp2_it7 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp4_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_s_fu_848_p2))) begin
            ap_reg_ppiten_pp4_it0 <= ap_const_logic_0;
        end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
            ap_reg_ppiten_pp4_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp4_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_lv1_0 == tmp_s_reg_1203) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm))) begin
            ap_reg_ppiten_pp4_it1 <= ap_const_logic_1;
        end else if ((((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_3_fu_613_p2)) | ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_s_reg_1203)))) begin
            ap_reg_ppiten_pp4_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp4_it10 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it10
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it10 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it10 <= ap_reg_ppiten_pp4_it9;
        end
    end
end

/// ap_reg_ppiten_pp4_it11 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it11
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it11 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it11 <= ap_reg_ppiten_pp4_it10;
        end
    end
end

/// ap_reg_ppiten_pp4_it12 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it12
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it12 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it12 <= ap_reg_ppiten_pp4_it11;
        end
    end
end

/// ap_reg_ppiten_pp4_it13 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it13
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it13 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it13 <= ap_reg_ppiten_pp4_it12;
        end
    end
end

/// ap_reg_ppiten_pp4_it14 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it14
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it14 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it14 <= ap_reg_ppiten_pp4_it13;
        end
    end
end

/// ap_reg_ppiten_pp4_it15 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it15
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it15 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it15 <= ap_reg_ppiten_pp4_it14;
        end
    end
end

/// ap_reg_ppiten_pp4_it16 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it16
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it16 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it16 <= ap_reg_ppiten_pp4_it15;
        end
    end
end

/// ap_reg_ppiten_pp4_it17 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it17
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it17 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it17 <= ap_reg_ppiten_pp4_it16;
        end
    end
end

/// ap_reg_ppiten_pp4_it18 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it18
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it18 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it18 <= ap_reg_ppiten_pp4_it17;
        end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
            ap_reg_ppiten_pp4_it18 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp4_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it2 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it2 <= ap_reg_ppiten_pp4_it1;
        end
    end
end

/// ap_reg_ppiten_pp4_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it3 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it3 <= ap_reg_ppiten_pp4_it2;
        end
    end
end

/// ap_reg_ppiten_pp4_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it4 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it4 <= ap_reg_ppiten_pp4_it3;
        end
    end
end

/// ap_reg_ppiten_pp4_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it5 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it5 <= ap_reg_ppiten_pp4_it4;
        end
    end
end

/// ap_reg_ppiten_pp4_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it6 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it6 <= ap_reg_ppiten_pp4_it5;
        end
    end
end

/// ap_reg_ppiten_pp4_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it7 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it7 <= ap_reg_ppiten_pp4_it6;
        end
    end
end

/// ap_reg_ppiten_pp4_it8 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it8 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it8 <= ap_reg_ppiten_pp4_it7;
        end
    end
end

/// ap_reg_ppiten_pp4_it9 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp4_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp4_it9 <= ap_const_logic_0;
    end else begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp4_it9 <= ap_reg_ppiten_pp4_it8;
        end
    end
end

/// ap_reg_ppiten_pp5_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp5_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp5_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_lv1_0 == exitcond1_fu_1016_p2))) begin
            ap_reg_ppiten_pp5_it0 <= ap_const_logic_0;
        end else if ((ap_ST_st64_fsm_13 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp5_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp5_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp5_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp5_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & (ap_const_lv1_0 == exitcond1_fu_1016_p2))) begin
            ap_reg_ppiten_pp5_it1 <= ap_const_logic_1;
        end else if (((ap_ST_st64_fsm_13 == ap_CS_fsm) | ((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_lv1_0 == exitcond1_fu_1016_p2)))) begin
            ap_reg_ppiten_pp5_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp5_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp5_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp5_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)))) begin
            ap_reg_ppiten_pp5_it2 <= ap_reg_ppiten_pp5_it1;
        end else if ((ap_ST_st64_fsm_13 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp5_it2 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st25_fsm_10 == ap_CS_fsm)) begin
        b2_reg_488 <= b2_1_reg_1095;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        b2_reg_488 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st25_fsm_10 == ap_CS_fsm)) begin
        b_reg_500 <= b_1_fu_842_p2;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        b_reg_500 <= ap_const_lv32_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~(ap_const_lv1_0 == exitcond2_fu_670_p2))) begin
        i1_reg_536 <= ap_const_lv3_0;
    end else if (((ap_const_lv1_0 == exitcond7_reg_1124) & (ap_ST_st24_fsm_9 == ap_CS_fsm))) begin
        i1_reg_536 <= i_3_reg_1128;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
        i5_reg_560 <= ap_const_lv9_0;
    end else if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == tmp_s_reg_1203))) begin
        i5_reg_560 <= i_2_reg_1207;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_587_p2))) begin
        i_reg_477 <= i_1_fu_593_p2;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        i_reg_477 <= ap_const_lv9_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st64_fsm_13 == ap_CS_fsm)) begin
        indvar1_reg_571 <= ap_const_lv30_0;
    end else if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & (ap_const_lv1_0 == exitcond1_fu_1016_p2))) begin
        indvar1_reg_571 <= indvar_next1_fu_1021_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_5 == ap_CS_fsm)) begin
        indvar2_reg_524 <= ap_const_lv4_0;
    end else if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & (ap_const_lv1_0 == exitcond2_reg_1106))) begin
        indvar2_reg_524 <= indvar_next2_reg_1110;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
        indvar_reg_512 <= ap_const_lv4_0;
    end else if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & (exitcond_reg_1077 == ap_const_lv1_0))) begin
        indvar_reg_512 <= indvar_next_reg_1081;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
        total_distortion_reg_547 <= ap_const_lv32_0;
    end else if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_s_reg_1203_pp4_it1))) begin
        total_distortion_reg_547 <= total_distortion_1_reg_1274;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)))) begin
        ap_reg_ppstg_exitcond1_reg_1294_pp5_it1 <= exitcond1_reg_1294;
        ap_reg_ppstg_isIter_reg_1308_pp5_it1 <= isIter_reg_1308;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
        ap_reg_ppstg_exitcond2_reg_1106_pp2_it1 <= exitcond2_reg_1106;
        ap_reg_ppstg_exitcond2_reg_1106_pp2_it2 <= ap_reg_ppstg_exitcond2_reg_1106_pp2_it1;
        ap_reg_ppstg_exitcond2_reg_1106_pp2_it3 <= ap_reg_ppstg_exitcond2_reg_1106_pp2_it2;
        ap_reg_ppstg_exitcond2_reg_1106_pp2_it4 <= ap_reg_ppstg_exitcond2_reg_1106_pp2_it3;
        ap_reg_ppstg_exitcond2_reg_1106_pp2_it5 <= ap_reg_ppstg_exitcond2_reg_1106_pp2_it4;
        ap_reg_ppstg_exitcond2_reg_1106_pp2_it6 <= ap_reg_ppstg_exitcond2_reg_1106_pp2_it5;
        ap_reg_ppstg_indvar2_reg_524_pp2_it1 <= indvar2_reg_524;
        ap_reg_ppstg_indvar2_reg_524_pp2_it2 <= ap_reg_ppstg_indvar2_reg_524_pp2_it1;
        ap_reg_ppstg_indvar2_reg_524_pp2_it3 <= ap_reg_ppstg_indvar2_reg_524_pp2_it2;
        ap_reg_ppstg_indvar2_reg_524_pp2_it4 <= ap_reg_ppstg_indvar2_reg_524_pp2_it3;
        ap_reg_ppstg_indvar2_reg_524_pp2_it5 <= ap_reg_ppstg_indvar2_reg_524_pp2_it4;
        ap_reg_ppstg_indvar2_reg_524_pp2_it6 <= ap_reg_ppstg_indvar2_reg_524_pp2_it5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
        ap_reg_ppstg_exitcond_reg_1077_pp1_it1 <= exitcond_reg_1077;
        ap_reg_ppstg_exitcond_reg_1077_pp1_it2 <= ap_reg_ppstg_exitcond_reg_1077_pp1_it1;
        ap_reg_ppstg_exitcond_reg_1077_pp1_it3 <= ap_reg_ppstg_exitcond_reg_1077_pp1_it2;
        ap_reg_ppstg_exitcond_reg_1077_pp1_it4 <= ap_reg_ppstg_exitcond_reg_1077_pp1_it3;
        ap_reg_ppstg_exitcond_reg_1077_pp1_it5 <= ap_reg_ppstg_exitcond_reg_1077_pp1_it4;
        ap_reg_ppstg_exitcond_reg_1077_pp1_it6 <= ap_reg_ppstg_exitcond_reg_1077_pp1_it5;
        ap_reg_ppstg_indvar_reg_512_pp1_it1 <= indvar_reg_512;
        ap_reg_ppstg_indvar_reg_512_pp1_it2 <= ap_reg_ppstg_indvar_reg_512_pp1_it1;
        ap_reg_ppstg_indvar_reg_512_pp1_it3 <= ap_reg_ppstg_indvar_reg_512_pp1_it2;
        ap_reg_ppstg_indvar_reg_512_pp1_it4 <= ap_reg_ppstg_indvar_reg_512_pp1_it3;
        ap_reg_ppstg_indvar_reg_512_pp1_it5 <= ap_reg_ppstg_indvar_reg_512_pp1_it4;
        ap_reg_ppstg_indvar_reg_512_pp1_it6 <= ap_reg_ppstg_indvar_reg_512_pp1_it5;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm)) begin
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it1 <= tmp_10_reg_1225;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it10 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it9;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it11 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it10;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it12 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it11;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it13 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it12;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it14 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it13;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it15 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it14;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it16 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it15;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it17 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it16;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it2 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it1;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it3 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it2;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it4 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it3;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it5 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it4;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it6 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it5;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it7 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it6;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it8 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it7;
        ap_reg_ppstg_tmp_10_reg_1225_pp4_it9 <= ap_reg_ppstg_tmp_10_reg_1225_pp4_it8;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it1 <= tmp_s_reg_1203;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it10 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it9;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it11 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it10;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it12 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it11;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it13 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it12;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it14 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it13;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it15 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it14;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it16 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it15;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it17 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it16;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it18 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it17;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it2 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it1;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it3 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it2;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it4 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it3;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it5 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it4;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it6 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it5;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it7 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it6;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it8 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it7;
        ap_reg_ppstg_tmp_s_reg_1203_pp4_it9 <= ap_reg_ppstg_tmp_s_reg_1203_pp4_it8;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_5 == ap_CS_fsm)) begin
        b2_1_reg_1095 <= b2_1_fu_654_p2;
        kernel_info_in_addr_reg_1100 <= tmp_7_fu_660_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it1) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & (ap_const_lv1_0 == exitcond1_reg_1294))) begin
        c_buffer_load_reg_1312 <= c_buffer_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st23_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_reg_1124))) begin
        centre_buffer_count_addr_2_reg_1188 <= tmp_24_fu_799_p1;
        centre_buffer_sum_sq_addr_2_reg_1193 <= tmp_24_fu_799_p1;
        tmp_24_reg_1183[0] <= tmp_24_fu_799_p1[0];
tmp_24_reg_1183[1] <= tmp_24_fu_799_p1[1];
tmp_24_reg_1183[2] <= tmp_24_fu_799_p1[2];
tmp_24_reg_1183[3] <= tmp_24_fu_799_p1[3];
tmp_24_reg_1183[4] <= tmp_24_fu_799_p1[4];
tmp_24_reg_1183[5] <= tmp_24_fu_799_p1[5];
tmp_24_reg_1183[6] <= tmp_24_fu_799_p1[6];
tmp_24_reg_1183[7] <= tmp_24_fu_799_p1[7];
tmp_24_reg_1183[8] <= tmp_24_fu_799_p1[8];
tmp_24_reg_1183[9] <= tmp_24_fu_799_p1[9];
tmp_24_reg_1183[10] <= tmp_24_fu_799_p1[10];
tmp_24_reg_1183[11] <= tmp_24_fu_799_p1[11];
tmp_24_reg_1183[12] <= tmp_24_fu_799_p1[12];
tmp_24_reg_1183[13] <= tmp_24_fu_799_p1[13];
tmp_24_reg_1183[14] <= tmp_24_fu_799_p1[14];
tmp_24_reg_1183[15] <= tmp_24_fu_799_p1[15];
tmp_24_reg_1183[16] <= tmp_24_fu_799_p1[16];
tmp_24_reg_1183[17] <= tmp_24_fu_799_p1[17];
tmp_24_reg_1183[18] <= tmp_24_fu_799_p1[18];
tmp_24_reg_1183[19] <= tmp_24_fu_799_p1[19];
tmp_24_reg_1183[20] <= tmp_24_fu_799_p1[20];
tmp_24_reg_1183[21] <= tmp_24_fu_799_p1[21];
tmp_24_reg_1183[22] <= tmp_24_fu_799_p1[22];
tmp_24_reg_1183[23] <= tmp_24_fu_799_p1[23];
tmp_24_reg_1183[24] <= tmp_24_fu_799_p1[24];
tmp_24_reg_1183[25] <= tmp_24_fu_799_p1[25];
tmp_24_reg_1183[26] <= tmp_24_fu_799_p1[26];
tmp_24_reg_1183[27] <= tmp_24_fu_799_p1[27];
tmp_24_reg_1183[28] <= tmp_24_fu_799_p1[28];
tmp_24_reg_1183[29] <= tmp_24_fu_799_p1[29];
tmp_24_reg_1183[30] <= tmp_24_fu_799_p1[30];
tmp_24_reg_1183[31] <= tmp_24_fu_799_p1[31];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_lv1_0 == tmp_s_reg_1203) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm))) begin
        centre_buffer_count_load_reg_1236 <= centre_buffer_count_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_reg_ppstg_exitcond_reg_1077_pp1_it5 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
        data_points_in_addr_read_reg_1090 <= data_points_in_datain;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
        data_points_in_addr_reg_1066 <= tmp_4_fu_618_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)))) begin
        exitcond1_reg_1294 <= exitcond1_fu_1016_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
        exitcond2_reg_1106 <= exitcond2_fu_670_p2;
        indvar_next2_reg_1110 <= indvar_next2_fu_676_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st22_fsm_7 == ap_CS_fsm)) begin
        exitcond7_reg_1124 <= exitcond7_fu_693_p2;
        i_3_reg_1128 <= i_3_fu_699_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
        exitcond_reg_1077 <= exitcond_fu_631_p2;
        indvar_next_reg_1081 <= indvar_next_fu_637_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0))) begin
        i_2_reg_1207 <= i_2_fu_853_p2;
        tmp_s_reg_1203 <= tmp_s_fu_848_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & (ap_const_lv1_0 == exitcond_fu_631_p2))) begin
        isIter0_reg_1086 <= isIter0_fu_643_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & (ap_const_lv1_0 == exitcond2_fu_670_p2))) begin
        isIter1_reg_1115 <= isIter1_fu_682_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & (ap_const_lv1_0 == exitcond1_fu_1016_p2))) begin
        isIter_reg_1308 <= isIter_fu_1032_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_1106_pp2_it5) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
        kernel_info_in_addr_read_reg_1119 <= kernel_info_in_datain;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        lim_reg_1058[1] <= lim_fu_608_p2[1];
lim_reg_1058[2] <= lim_fu_608_p2[2];
lim_reg_1058[3] <= lim_fu_608_p2[3];
lim_reg_1058[4] <= lim_fu_608_p2[4];
lim_reg_1058[5] <= lim_fu_608_p2[5];
lim_reg_1058[6] <= lim_fu_608_p2[6];
lim_reg_1058[7] <= lim_fu_608_p2[7];
lim_reg_1058[8] <= lim_fu_608_p2[8];
lim_reg_1058[9] <= lim_fu_608_p2[9];
lim_reg_1058[10] <= lim_fu_608_p2[10];
lim_reg_1058[11] <= lim_fu_608_p2[11];
lim_reg_1058[12] <= lim_fu_608_p2[12];
lim_reg_1058[13] <= lim_fu_608_p2[13];
lim_reg_1058[14] <= lim_fu_608_p2[14];
lim_reg_1058[15] <= lim_fu_608_p2[15];
lim_reg_1058[16] <= lim_fu_608_p2[16];
lim_reg_1058[17] <= lim_fu_608_p2[17];
lim_reg_1058[18] <= lim_fu_608_p2[18];
lim_reg_1058[19] <= lim_fu_608_p2[19];
lim_reg_1058[20] <= lim_fu_608_p2[20];
lim_reg_1058[21] <= lim_fu_608_p2[21];
lim_reg_1058[22] <= lim_fu_608_p2[22];
lim_reg_1058[23] <= lim_fu_608_p2[23];
lim_reg_1058[24] <= lim_fu_608_p2[24];
lim_reg_1058[25] <= lim_fu_608_p2[25];
lim_reg_1058[26] <= lim_fu_608_p2[26];
lim_reg_1058[27] <= lim_fu_608_p2[27];
lim_reg_1058[28] <= lim_fu_608_p2[28];
lim_reg_1058[29] <= lim_fu_608_p2[29];
lim_reg_1058[30] <= lim_fu_608_p2[30];
lim_reg_1058[31] <= lim_fu_608_p2[31];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == tmp_s_reg_1203))) begin
        p_s_reg_1262 <= p_s_fu_891_p3;
        total_distortion_1_reg_1274 <= total_distortion_1_fu_912_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((((ap_ST_st23_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_reg_1124)) | ((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == tmp_s_reg_1203)))) begin
        reg_583 <= centre_buffer_2_wgtCent_value_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_const_lv1_0 == tmp_s_fu_848_p2))) begin
        tmp_10_reg_1225 <= tmp_10_fu_880_p2;
        tmp_6_reg_1212[0] <= tmp_6_fu_863_p1[0];
tmp_6_reg_1212[1] <= tmp_6_fu_863_p1[1];
tmp_6_reg_1212[2] <= tmp_6_fu_863_p1[2];
tmp_6_reg_1212[3] <= tmp_6_fu_863_p1[3];
tmp_6_reg_1212[4] <= tmp_6_fu_863_p1[4];
tmp_6_reg_1212[5] <= tmp_6_fu_863_p1[5];
tmp_6_reg_1212[6] <= tmp_6_fu_863_p1[6];
tmp_6_reg_1212[7] <= tmp_6_fu_863_p1[7];
tmp_6_reg_1212[8] <= tmp_6_fu_863_p1[8];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st64_fsm_13 == ap_CS_fsm)) begin
        tmp_14_add_i32_shr_cast_reg_1289[0] <= tmp_14_add_i32_shr_cast_fu_1012_p1[0];
tmp_14_add_i32_shr_cast_reg_1289[1] <= tmp_14_add_i32_shr_cast_fu_1012_p1[1];
tmp_14_add_i32_shr_cast_reg_1289[2] <= tmp_14_add_i32_shr_cast_fu_1012_p1[2];
tmp_14_add_i32_shr_cast_reg_1289[3] <= tmp_14_add_i32_shr_cast_fu_1012_p1[3];
tmp_14_add_i32_shr_cast_reg_1289[4] <= tmp_14_add_i32_shr_cast_fu_1012_p1[4];
tmp_14_add_i32_shr_cast_reg_1289[5] <= tmp_14_add_i32_shr_cast_fu_1012_p1[5];
tmp_14_add_i32_shr_cast_reg_1289[6] <= tmp_14_add_i32_shr_cast_fu_1012_p1[6];
tmp_14_add_i32_shr_cast_reg_1289[7] <= tmp_14_add_i32_shr_cast_fu_1012_p1[7];
tmp_14_add_i32_shr_cast_reg_1289[8] <= tmp_14_add_i32_shr_cast_fu_1012_p1[8];
tmp_14_add_i32_shr_cast_reg_1289[9] <= tmp_14_add_i32_shr_cast_fu_1012_p1[9];
tmp_14_add_i32_shr_cast_reg_1289[10] <= tmp_14_add_i32_shr_cast_fu_1012_p1[10];
tmp_14_add_i32_shr_cast_reg_1289[11] <= tmp_14_add_i32_shr_cast_fu_1012_p1[11];
tmp_14_add_i32_shr_cast_reg_1289[12] <= tmp_14_add_i32_shr_cast_fu_1012_p1[12];
tmp_14_add_i32_shr_cast_reg_1289[13] <= tmp_14_add_i32_shr_cast_fu_1012_p1[13];
tmp_14_add_i32_shr_cast_reg_1289[14] <= tmp_14_add_i32_shr_cast_fu_1012_p1[14];
tmp_14_add_i32_shr_cast_reg_1289[15] <= tmp_14_add_i32_shr_cast_fu_1012_p1[15];
tmp_14_add_i32_shr_cast_reg_1289[16] <= tmp_14_add_i32_shr_cast_fu_1012_p1[16];
tmp_14_add_i32_shr_cast_reg_1289[17] <= tmp_14_add_i32_shr_cast_fu_1012_p1[17];
tmp_14_add_i32_shr_cast_reg_1289[18] <= tmp_14_add_i32_shr_cast_fu_1012_p1[18];
tmp_14_add_i32_shr_cast_reg_1289[19] <= tmp_14_add_i32_shr_cast_fu_1012_p1[19];
tmp_14_add_i32_shr_cast_reg_1289[20] <= tmp_14_add_i32_shr_cast_fu_1012_p1[20];
tmp_14_add_i32_shr_cast_reg_1289[21] <= tmp_14_add_i32_shr_cast_fu_1012_p1[21];
tmp_14_add_i32_shr_cast_reg_1289[22] <= tmp_14_add_i32_shr_cast_fu_1012_p1[22];
tmp_14_add_i32_shr_cast_reg_1289[23] <= tmp_14_add_i32_shr_cast_fu_1012_p1[23];
tmp_14_add_i32_shr_cast_reg_1289[24] <= tmp_14_add_i32_shr_cast_fu_1012_p1[24];
tmp_14_add_i32_shr_cast_reg_1289[25] <= tmp_14_add_i32_shr_cast_fu_1012_p1[25];
tmp_14_add_i32_shr_cast_reg_1289[26] <= tmp_14_add_i32_shr_cast_fu_1012_p1[26];
tmp_14_add_i32_shr_cast_reg_1289[27] <= tmp_14_add_i32_shr_cast_fu_1012_p1[27];
tmp_14_add_i32_shr_cast_reg_1289[28] <= tmp_14_add_i32_shr_cast_fu_1012_p1[28];
tmp_14_add_i32_shr_cast_reg_1289[29] <= tmp_14_add_i32_shr_cast_fu_1012_p1[29];
        tmp_14_add_i32_shr_reg_1284 <= tmp_14_add_i32_shr_fu_1008_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it18) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_s_reg_1203_pp4_it17))) begin
        tmp_14_cast4_reg_1279 <= tmp_14_cast4_fu_924_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st22_fsm_7 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_fu_693_p2))) begin
        tmp_20_reg_1143 <= tmp_20_fu_736_p2;
        tmp_21_reg_1133 <= tmp_21_fu_709_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(ap_const_lv1_0 == tmp_3_fu_613_p2))) begin
        tmp_9_cast_cast_reg_1072[0] <= tmp_9_cast_cast_fu_628_p1[0];
tmp_9_cast_cast_reg_1072[1] <= tmp_9_cast_cast_fu_628_p1[1];
tmp_9_cast_cast_reg_1072[2] <= tmp_9_cast_cast_fu_628_p1[2];
tmp_9_cast_cast_reg_1072[3] <= tmp_9_cast_cast_fu_628_p1[3];
tmp_9_cast_cast_reg_1072[4] <= tmp_9_cast_cast_fu_628_p1[4];
tmp_9_cast_cast_reg_1072[5] <= tmp_9_cast_cast_fu_628_p1[5];
tmp_9_cast_cast_reg_1072[6] <= tmp_9_cast_cast_fu_628_p1[6];
tmp_9_cast_cast_reg_1072[7] <= tmp_9_cast_cast_fu_628_p1[7];
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st68_fsm_15 == ap_CS_fsm)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st68_fsm_15 == ap_CS_fsm)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// c_buffer_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it18 or tmp_13_fu_930_p1 or tmp_25_2_fu_959_p1)
begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp4_it18)) begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            c_buffer_address0 = tmp_25_2_fu_959_p1;
        end else if ((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm)) begin
            c_buffer_address0 = tmp_13_fu_930_p1;
        end else begin
            c_buffer_address0 = 'bx;
        end
    end else begin
        c_buffer_address0 = 'bx;
    end
end

/// c_buffer_address1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it18 or ap_reg_ppiten_pp5_it0 or tmp_25_1_fu_945_p1 or tmp_15_fu_1027_p1)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it18))) begin
        c_buffer_address1 = tmp_25_1_fu_945_p1;
    end else if (((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it0))) begin
        c_buffer_address1 = tmp_15_fu_1027_p1;
    end else begin
        c_buffer_address1 = 'bx;
    end
end

/// c_buffer_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it18)
begin
    if ((((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it18)) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it18) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)))) begin
        c_buffer_ce0 = ap_const_logic_1;
    end else begin
        c_buffer_ce0 = ap_const_logic_0;
    end
end

/// c_buffer_ce1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it18 or ap_reg_ppiten_pp5_it0 or ap_sig_bdd_475 or ap_reg_ppiten_pp5_it2)
begin
    if ((((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it18)) | ((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2))))) begin
        c_buffer_ce1 = ap_const_logic_1;
    end else begin
        c_buffer_ce1 = ap_const_logic_0;
    end
end

/// c_buffer_d0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it18 or grp_fu_898_p2 or grp_fu_918_p2)
begin
    if ((ap_const_logic_1 == ap_reg_ppiten_pp4_it18)) begin
        if ((ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) begin
            c_buffer_d0 = grp_fu_918_p2;
        end else if ((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm)) begin
            c_buffer_d0 = grp_fu_898_p2;
        end else begin
            c_buffer_d0 = 'bx;
        end
    end else begin
        c_buffer_d0 = 'bx;
    end
end

/// c_buffer_we0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it18 or ap_reg_ppstg_tmp_s_reg_1203_pp4_it17 or ap_reg_ppstg_tmp_s_reg_1203_pp4_it18)
begin
    if ((((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it18) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_s_reg_1203_pp4_it17)) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it18) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_s_reg_1203_pp4_it18)))) begin
        c_buffer_we0 = ap_const_logic_1;
    end else begin
        c_buffer_we0 = ap_const_logic_0;
    end
end

/// c_buffer_we1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it18 or ap_reg_ppstg_tmp_s_reg_1203_pp4_it17)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it18) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_s_reg_1203_pp4_it17))) begin
        c_buffer_we1 = ap_const_logic_1;
    end else begin
        c_buffer_we1 = ap_const_logic_0;
    end
end

/// centre_buffer_0_wgtCent_value_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0 or tmp_24_fu_799_p1 or tmp_6_reg_1212 or tmp_2_fu_599_p1 or tmp_25_fu_766_p1)
begin
    if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        centre_buffer_0_wgtCent_value_address0 = tmp_24_fu_799_p1;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_0_wgtCent_value_address0 = tmp_2_fu_599_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm))) begin
        centre_buffer_0_wgtCent_value_address0 = tmp_6_reg_1212;
    end else if ((ap_ST_st22_fsm_7 == ap_CS_fsm)) begin
        centre_buffer_0_wgtCent_value_address0 = tmp_25_fu_766_p1;
    end else begin
        centre_buffer_0_wgtCent_value_address0 = 'bx;
    end
end

/// centre_buffer_0_wgtCent_value_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0)
begin
    if (((ap_ST_st23_fsm_8 == ap_CS_fsm) | (ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st22_fsm_7 == ap_CS_fsm) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)))) begin
        centre_buffer_0_wgtCent_value_ce0 = ap_const_logic_1;
    end else begin
        centre_buffer_0_wgtCent_value_ce0 = ap_const_logic_0;
    end
end

/// centre_buffer_0_wgtCent_value_d0 assign process. ///
always @ (ap_CS_fsm or tmp_28_fu_807_p2)
begin
    if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        centre_buffer_0_wgtCent_value_d0 = tmp_28_fu_807_p2;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_0_wgtCent_value_d0 = ap_const_lv32_0;
    end else begin
        centre_buffer_0_wgtCent_value_d0 = 'bx;
    end
end

/// centre_buffer_0_wgtCent_value_we0 assign process. ///
always @ (ap_CS_fsm or exitcond7_reg_1124 or exitcond9_fu_587_p2)
begin
    if ((((ap_ST_st23_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_reg_1124)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_587_p2)))) begin
        centre_buffer_0_wgtCent_value_we0 = ap_const_logic_1;
    end else begin
        centre_buffer_0_wgtCent_value_we0 = ap_const_logic_0;
    end
end

/// centre_buffer_1_wgtCent_value_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0 or tmp_24_fu_799_p1 or tmp_6_reg_1212 or tmp_2_fu_599_p1 or tmp_25_fu_766_p1)
begin
    if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        centre_buffer_1_wgtCent_value_address0 = tmp_24_fu_799_p1;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_1_wgtCent_value_address0 = tmp_2_fu_599_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm))) begin
        centre_buffer_1_wgtCent_value_address0 = tmp_6_reg_1212;
    end else if ((ap_ST_st22_fsm_7 == ap_CS_fsm)) begin
        centre_buffer_1_wgtCent_value_address0 = tmp_25_fu_766_p1;
    end else begin
        centre_buffer_1_wgtCent_value_address0 = 'bx;
    end
end

/// centre_buffer_1_wgtCent_value_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0)
begin
    if (((ap_ST_st23_fsm_8 == ap_CS_fsm) | (ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st22_fsm_7 == ap_CS_fsm) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)))) begin
        centre_buffer_1_wgtCent_value_ce0 = ap_const_logic_1;
    end else begin
        centre_buffer_1_wgtCent_value_ce0 = ap_const_logic_0;
    end
end

/// centre_buffer_1_wgtCent_value_d0 assign process. ///
always @ (ap_CS_fsm or tmp_35_1_fu_814_p2)
begin
    if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        centre_buffer_1_wgtCent_value_d0 = tmp_35_1_fu_814_p2;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_1_wgtCent_value_d0 = ap_const_lv32_0;
    end else begin
        centre_buffer_1_wgtCent_value_d0 = 'bx;
    end
end

/// centre_buffer_1_wgtCent_value_we0 assign process. ///
always @ (ap_CS_fsm or exitcond7_reg_1124 or exitcond9_fu_587_p2)
begin
    if ((((ap_ST_st23_fsm_8 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond7_reg_1124)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_587_p2)))) begin
        centre_buffer_1_wgtCent_value_we0 = ap_const_logic_1;
    end else begin
        centre_buffer_1_wgtCent_value_we0 = ap_const_logic_0;
    end
end

/// centre_buffer_2_wgtCent_value_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0 or tmp_24_reg_1183 or tmp_6_reg_1212 or tmp_2_fu_599_p1 or tmp_25_fu_766_p1)
begin
    if ((ap_ST_st24_fsm_9 == ap_CS_fsm)) begin
        centre_buffer_2_wgtCent_value_address0 = tmp_24_reg_1183;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_2_wgtCent_value_address0 = tmp_2_fu_599_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm))) begin
        centre_buffer_2_wgtCent_value_address0 = tmp_6_reg_1212;
    end else if ((ap_ST_st22_fsm_7 == ap_CS_fsm)) begin
        centre_buffer_2_wgtCent_value_address0 = tmp_25_fu_766_p1;
    end else begin
        centre_buffer_2_wgtCent_value_address0 = 'bx;
    end
end

/// centre_buffer_2_wgtCent_value_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st22_fsm_7 == ap_CS_fsm) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) | (ap_ST_st24_fsm_9 == ap_CS_fsm))) begin
        centre_buffer_2_wgtCent_value_ce0 = ap_const_logic_1;
    end else begin
        centre_buffer_2_wgtCent_value_ce0 = ap_const_logic_0;
    end
end

/// centre_buffer_2_wgtCent_value_d0 assign process. ///
always @ (ap_CS_fsm or tmp_35_2_fu_835_p2)
begin
    if ((ap_ST_st24_fsm_9 == ap_CS_fsm)) begin
        centre_buffer_2_wgtCent_value_d0 = tmp_35_2_fu_835_p2;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_2_wgtCent_value_d0 = ap_const_lv32_0;
    end else begin
        centre_buffer_2_wgtCent_value_d0 = 'bx;
    end
end

/// centre_buffer_2_wgtCent_value_we0 assign process. ///
always @ (ap_CS_fsm or exitcond7_reg_1124 or exitcond9_fu_587_p2)
begin
    if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_587_p2)) | ((ap_const_lv1_0 == exitcond7_reg_1124) & (ap_ST_st24_fsm_9 == ap_CS_fsm)))) begin
        centre_buffer_2_wgtCent_value_we0 = ap_const_logic_1;
    end else begin
        centre_buffer_2_wgtCent_value_we0 = ap_const_logic_0;
    end
end

/// centre_buffer_count_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0 or tmp_24_fu_799_p1 or centre_buffer_count_addr_2_reg_1188 or tmp_6_fu_863_p1 or tmp_2_fu_599_p1)
begin
    if ((ap_ST_st24_fsm_9 == ap_CS_fsm)) begin
        centre_buffer_count_address0 = centre_buffer_count_addr_2_reg_1188;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_count_address0 = tmp_2_fu_599_p1;
    end else if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0))) begin
        centre_buffer_count_address0 = tmp_6_fu_863_p1;
    end else if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        centre_buffer_count_address0 = tmp_24_fu_799_p1;
    end else begin
        centre_buffer_count_address0 = 'bx;
    end
end

/// centre_buffer_count_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0)
begin
    if (((ap_ST_st23_fsm_8 == ap_CS_fsm) | (ap_ST_st2_fsm_1 == ap_CS_fsm) | ((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it0)) | (ap_ST_st24_fsm_9 == ap_CS_fsm))) begin
        centre_buffer_count_ce0 = ap_const_logic_1;
    end else begin
        centre_buffer_count_ce0 = ap_const_logic_0;
    end
end

/// centre_buffer_count_d0 assign process. ///
always @ (ap_CS_fsm or tmp_26_fu_821_p2)
begin
    if ((ap_ST_st24_fsm_9 == ap_CS_fsm)) begin
        centre_buffer_count_d0 = tmp_26_fu_821_p2;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_count_d0 = ap_const_lv32_0;
    end else begin
        centre_buffer_count_d0 = 'bx;
    end
end

/// centre_buffer_count_we0 assign process. ///
always @ (ap_CS_fsm or exitcond7_reg_1124 or exitcond9_fu_587_p2)
begin
    if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_587_p2)) | ((ap_const_lv1_0 == exitcond7_reg_1124) & (ap_ST_st24_fsm_9 == ap_CS_fsm)))) begin
        centre_buffer_count_we0 = ap_const_logic_1;
    end else begin
        centre_buffer_count_we0 = ap_const_logic_0;
    end
end

/// centre_buffer_sum_sq_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0 or tmp_24_fu_799_p1 or centre_buffer_sum_sq_addr_2_reg_1193 or tmp_6_reg_1212 or tmp_2_fu_599_p1)
begin
    if ((ap_ST_st24_fsm_9 == ap_CS_fsm)) begin
        centre_buffer_sum_sq_address0 = centre_buffer_sum_sq_addr_2_reg_1193;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_sum_sq_address0 = tmp_2_fu_599_p1;
    end else if (((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm))) begin
        centre_buffer_sum_sq_address0 = tmp_6_reg_1212;
    end else if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        centre_buffer_sum_sq_address0 = tmp_24_fu_799_p1;
    end else begin
        centre_buffer_sum_sq_address0 = 'bx;
    end
end

/// centre_buffer_sum_sq_ce0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp4_it0)
begin
    if (((ap_ST_st23_fsm_8 == ap_CS_fsm) | (ap_ST_st2_fsm_1 == ap_CS_fsm) | ((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm)) | (ap_ST_st24_fsm_9 == ap_CS_fsm))) begin
        centre_buffer_sum_sq_ce0 = ap_const_logic_1;
    end else begin
        centre_buffer_sum_sq_ce0 = ap_const_logic_0;
    end
end

/// centre_buffer_sum_sq_d0 assign process. ///
always @ (ap_CS_fsm or tmp_27_fu_828_p2)
begin
    if ((ap_ST_st24_fsm_9 == ap_CS_fsm)) begin
        centre_buffer_sum_sq_d0 = tmp_27_fu_828_p2;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        centre_buffer_sum_sq_d0 = ap_const_lv32_0;
    end else begin
        centre_buffer_sum_sq_d0 = 'bx;
    end
end

/// centre_buffer_sum_sq_we0 assign process. ///
always @ (ap_CS_fsm or exitcond7_reg_1124 or exitcond9_fu_587_p2)
begin
    if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond9_fu_587_p2)) | ((ap_const_lv1_0 == exitcond7_reg_1124) & (ap_ST_st24_fsm_9 == ap_CS_fsm)))) begin
        centre_buffer_sum_sq_we0 = ap_const_logic_1;
    end else begin
        centre_buffer_sum_sq_we0 = ap_const_logic_0;
    end
end

/// centres_out_req_din assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond1_reg_1294_pp5_it1 or ap_sig_bdd_475 or ap_reg_ppiten_pp5_it2 or ap_reg_ppstg_isIter_reg_1308_pp5_it1)
begin
    if ((((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1294_pp5_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_lv1_0 == ap_reg_ppstg_isIter_reg_1308_pp5_it1)) | ((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1294_pp5_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2))))) begin
        centres_out_req_din = ap_const_logic_1;
    end else begin
        centres_out_req_din = ap_const_logic_0;
    end
end

/// centres_out_req_write assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond1_reg_1294_pp5_it1 or ap_sig_bdd_475 or ap_reg_ppiten_pp5_it2 or ap_reg_ppstg_isIter_reg_1308_pp5_it1)
begin
    if ((((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1294_pp5_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_lv1_0 == ap_reg_ppstg_isIter_reg_1308_pp5_it1)) | ((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1294_pp5_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2))))) begin
        centres_out_req_write = ap_const_logic_1;
    end else begin
        centres_out_req_write = ap_const_logic_0;
    end
end

/// data_points_in_req_write assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp1_it1 or exitcond_reg_1077 or ap_sig_bdd_97 or ap_reg_ppiten_pp1_it6 or isIter0_reg_1086)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & (exitcond_reg_1077 == ap_const_lv1_0) & ~(ap_const_lv1_0 == isIter0_reg_1086))) begin
        data_points_in_req_write = ap_const_logic_1;
    end else begin
        data_points_in_req_write = ap_const_logic_0;
    end
end

/// data_points_in_rsp_read assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond_reg_1077_pp1_it5 or ap_sig_bdd_97 or ap_reg_ppiten_pp1_it6)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_reg_ppstg_exitcond_reg_1077_pp1_it5 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)))) begin
        data_points_in_rsp_read = ap_const_logic_1;
    end else begin
        data_points_in_rsp_read = ap_const_logic_0;
    end
end

/// distortion_out_ap_vld assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st68_fsm_15 == ap_CS_fsm)) begin
        distortion_out_ap_vld = ap_const_logic_1;
    end else begin
        distortion_out_ap_vld = ap_const_logic_0;
    end
end

/// i5_phi_fu_564_p4 assign process. ///
always @ (ap_CS_fsm or i5_reg_560 or ap_reg_ppiten_pp4_it1 or tmp_s_reg_1203 or i_2_reg_1207)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it1) & (ap_const_lv1_0 == tmp_s_reg_1203))) begin
        i5_phi_fu_564_p4 = i_2_reg_1207;
    end else begin
        i5_phi_fu_564_p4 = i5_reg_560;
    end
end

/// i_buffer_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp2_it7 or tmp_29_fu_688_p1 or tmp_17_fu_719_p1 or tmp_19_fu_780_p1)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it7))) begin
        i_buffer_address0 = tmp_29_fu_688_p1;
    end else if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        i_buffer_address0 = tmp_19_fu_780_p1;
    end else if ((ap_ST_st22_fsm_7 == ap_CS_fsm)) begin
        i_buffer_address0 = tmp_17_fu_719_p1;
    end else begin
        i_buffer_address0 = 'bx;
    end
end

/// i_buffer_ce0 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_131 or ap_reg_ppiten_pp2_it6 or ap_reg_ppiten_pp2_it7)
begin
    if (((ap_ST_st23_fsm_8 == ap_CS_fsm) | (ap_ST_st22_fsm_7 == ap_CS_fsm) | ((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it7) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6))))) begin
        i_buffer_ce0 = ap_const_logic_1;
    end else begin
        i_buffer_ce0 = ap_const_logic_0;
    end
end

/// i_buffer_we0 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_131 or ap_reg_ppiten_pp2_it6 or ap_reg_ppiten_pp2_it7 or ap_reg_ppstg_exitcond2_reg_1106_pp2_it6)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it7) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_1106_pp2_it6))) begin
        i_buffer_we0 = ap_const_logic_1;
    end else begin
        i_buffer_we0 = ap_const_logic_0;
    end
end

/// indvar2_phi_fu_528_p4 assign process. ///
always @ (ap_CS_fsm or indvar2_reg_524 or ap_reg_ppiten_pp2_it1 or exitcond2_reg_1106 or indvar_next2_reg_1110)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1) & (ap_const_lv1_0 == exitcond2_reg_1106))) begin
        indvar2_phi_fu_528_p4 = indvar_next2_reg_1110;
    end else begin
        indvar2_phi_fu_528_p4 = indvar2_reg_524;
    end
end

/// indvar_phi_fu_516_p4 assign process. ///
always @ (ap_CS_fsm or indvar_reg_512 or ap_reg_ppiten_pp1_it1 or exitcond_reg_1077 or indvar_next_reg_1081)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & (exitcond_reg_1077 == ap_const_lv1_0))) begin
        indvar_phi_fu_516_p4 = indvar_next_reg_1081;
    end else begin
        indvar_phi_fu_516_p4 = indvar_reg_512;
    end
end

/// kernel_info_in_req_write assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp2_it1 or exitcond2_reg_1106 or ap_sig_bdd_131 or ap_reg_ppiten_pp2_it6 or isIter1_reg_1115)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it1) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & (ap_const_lv1_0 == exitcond2_reg_1106) & ~(ap_const_lv1_0 == isIter1_reg_1115))) begin
        kernel_info_in_req_write = ap_const_logic_1;
    end else begin
        kernel_info_in_req_write = ap_const_logic_0;
    end
end

/// kernel_info_in_rsp_read assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond2_reg_1106_pp2_it5 or ap_sig_bdd_131 or ap_reg_ppiten_pp2_it6)
begin
    if (((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_1106_pp2_it5) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)))) begin
        kernel_info_in_rsp_read = ap_const_logic_1;
    end else begin
        kernel_info_in_rsp_read = ap_const_logic_0;
    end
end

/// p_buffer_address0 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp1_it7 or tmp_14_fu_649_p1 or tmp_23_fu_746_p1)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it7))) begin
        p_buffer_address0 = tmp_14_fu_649_p1;
    end else if ((ap_ST_st22_fsm_7 == ap_CS_fsm)) begin
        p_buffer_address0 = tmp_23_fu_746_p1;
    end else begin
        p_buffer_address0 = 'bx;
    end
end

/// p_buffer_address1 assign process. ///
always @ (ap_CS_fsm or tmp_29_1_fu_761_p1 or tmp_29_2_fu_794_p1)
begin
    if ((ap_ST_st23_fsm_8 == ap_CS_fsm)) begin
        p_buffer_address1 = tmp_29_2_fu_794_p1;
    end else if ((ap_ST_st22_fsm_7 == ap_CS_fsm)) begin
        p_buffer_address1 = tmp_29_1_fu_761_p1;
    end else begin
        p_buffer_address1 = 'bx;
    end
end

/// p_buffer_ce0 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_97 or ap_reg_ppiten_pp1_it6 or ap_reg_ppiten_pp1_it7)
begin
    if (((ap_ST_st22_fsm_7 == ap_CS_fsm) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it7) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6))))) begin
        p_buffer_ce0 = ap_const_logic_1;
    end else begin
        p_buffer_ce0 = ap_const_logic_0;
    end
end

/// p_buffer_ce1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st23_fsm_8 == ap_CS_fsm) | (ap_ST_st22_fsm_7 == ap_CS_fsm))) begin
        p_buffer_ce1 = ap_const_logic_1;
    end else begin
        p_buffer_ce1 = ap_const_logic_0;
    end
end

/// p_buffer_we0 assign process. ///
always @ (ap_CS_fsm or ap_sig_bdd_97 or ap_reg_ppiten_pp1_it6 or ap_reg_ppiten_pp1_it7 or ap_reg_ppstg_exitcond_reg_1077_pp1_it6)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it7) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_reg_1077_pp1_it6))) begin
        p_buffer_we0 = ap_const_logic_1;
    end else begin
        p_buffer_we0 = ap_const_logic_0;
    end
end

/// total_distortion_phi_fu_552_p4 assign process. ///
always @ (ap_CS_fsm or total_distortion_reg_547 or ap_reg_ppiten_pp4_it2 or ap_reg_ppstg_tmp_s_reg_1203_pp4_it1 or total_distortion_1_reg_1274)
begin
    if (((ap_ST_pp4_stg0_fsm_11 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp4_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_s_reg_1203_pp4_it1))) begin
        total_distortion_phi_fu_552_p4 = total_distortion_1_reg_1274;
    end else begin
        total_distortion_phi_fu_552_p4 = total_distortion_reg_547;
    end
end
always @ (ap_start or ap_CS_fsm or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_97 or ap_reg_ppiten_pp1_it6 or ap_reg_ppiten_pp1_it7 or ap_reg_ppiten_pp2_it0 or ap_reg_ppiten_pp2_it1 or ap_sig_bdd_131 or ap_reg_ppiten_pp2_it6 or ap_reg_ppiten_pp2_it7 or ap_reg_ppiten_pp4_it0 or ap_reg_ppiten_pp4_it1 or ap_reg_ppiten_pp4_it17 or ap_reg_ppiten_pp4_it18 or tmp_3_fu_613_p2 or exitcond_fu_631_p2 or exitcond2_fu_670_p2 or exitcond7_fu_693_p2 or tmp_s_fu_848_p2 or exitcond1_fu_1016_p2 or ap_reg_ppiten_pp5_it0 or ap_reg_ppiten_pp5_it1 or ap_sig_bdd_475 or ap_reg_ppiten_pp5_it2 or exitcond9_fu_587_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if ((ap_const_lv1_0 == exitcond9_fu_587_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st3_fsm_2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st4_fsm_3 : 
            if (~(ap_const_lv1_0 == tmp_3_fu_613_p2)) begin
                ap_NS_fsm = ap_ST_pp4_stg0_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        ap_ST_pp1_stg0_fsm_4 : 
            if ((~((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it7) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & ~(ap_const_lv1_0 == exitcond_fu_631_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if ((((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it7) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_97 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it6)) & ~(ap_const_lv1_0 == exitcond_fu_631_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
                ap_NS_fsm = ap_ST_st13_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        ap_ST_st13_fsm_5 : 
            ap_NS_fsm = ap_ST_pp2_stg0_fsm_6;
        ap_ST_pp2_stg0_fsm_6 : 
            if ((~((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it7) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~(ap_const_lv1_0 == exitcond2_fu_670_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp2_it1)))) begin
                ap_NS_fsm = ap_ST_pp2_stg0_fsm_6;
            end else if ((((ap_ST_pp2_stg0_fsm_6 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp2_it7) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) | ((ap_const_logic_1 == ap_reg_ppiten_pp2_it0) & ~(ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp2_it6)) & ~(ap_const_lv1_0 == exitcond2_fu_670_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp2_it1)))) begin
                ap_NS_fsm = ap_ST_st22_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_pp2_stg0_fsm_6;
            end
        ap_ST_st22_fsm_7 : 
            if ((ap_const_lv1_0 == exitcond7_fu_693_p2)) begin
                ap_NS_fsm = ap_ST_st23_fsm_8;
            end else begin
                ap_NS_fsm = ap_ST_st25_fsm_10;
            end
        ap_ST_st23_fsm_8 : 
            ap_NS_fsm = ap_ST_st24_fsm_9;
        ap_ST_st24_fsm_9 : 
            ap_NS_fsm = ap_ST_st22_fsm_7;
        ap_ST_st25_fsm_10 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_pp4_stg0_fsm_11 : 
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp4_it0) & ~(ap_const_lv1_0 == tmp_s_fu_848_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp4_it1))) begin
                ap_NS_fsm = ap_ST_pp4_stg1_fsm_12;
            end else begin
                ap_NS_fsm = ap_ST_st64_fsm_13;
            end
        ap_ST_pp4_stg1_fsm_12 : 
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp4_it18) & (ap_ST_pp4_stg1_fsm_12 == ap_CS_fsm) & ~(ap_const_logic_1 == ap_reg_ppiten_pp4_it17))) begin
                ap_NS_fsm = ap_ST_pp4_stg0_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st64_fsm_13;
            end
        ap_ST_st64_fsm_13 : 
            ap_NS_fsm = ap_ST_pp5_stg0_fsm_14;
        ap_ST_pp5_stg0_fsm_14 : 
            if ((~((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_lv1_0 == exitcond1_fu_1016_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp5_it1)))) begin
                ap_NS_fsm = ap_ST_pp5_stg0_fsm_14;
            end else if ((((ap_ST_pp5_stg0_fsm_14 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp5_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp5_it0) & ~(ap_sig_bdd_475 & (ap_const_logic_1 == ap_reg_ppiten_pp5_it2)) & ~(ap_const_lv1_0 == exitcond1_fu_1016_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp5_it1)))) begin
                ap_NS_fsm = ap_ST_st68_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_pp5_stg0_fsm_14;
            end
        ap_ST_st68_fsm_15 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_131 assign process. ///
always @ (kernel_info_in_rsp_empty_n or ap_reg_ppstg_exitcond2_reg_1106_pp2_it5)
begin
    ap_sig_bdd_131 = ((kernel_info_in_rsp_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_1106_pp2_it5));
end

/// ap_sig_bdd_475 assign process. ///
always @ (centres_out_req_full_n or ap_reg_ppstg_exitcond1_reg_1294_pp5_it1)
begin
    ap_sig_bdd_475 = ((centres_out_req_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond1_reg_1294_pp5_it1));
end

/// ap_sig_bdd_97 assign process. ///
always @ (data_points_in_rsp_empty_n or ap_reg_ppstg_exitcond_reg_1077_pp1_it5)
begin
    ap_sig_bdd_97 = ((data_points_in_rsp_empty_n == ap_const_logic_0) & (ap_reg_ppstg_exitcond_reg_1077_pp1_it5 == ap_const_lv1_0));
end
assign b2_1_fu_654_p2 = (b2_reg_488 + ap_const_lv32_C);
assign b_1_fu_842_p2 = (b_reg_500 + ap_const_lv32_8);
assign c_buffer_d1 = grp_fu_905_p2;
assign centres_out_address = ap_const_lv32_0;
assign centres_out_dataout = c_buffer_load_reg_1312;
assign centres_out_rsp_read = ap_const_logic_0;
assign centres_out_size = tmp_14_add_i32_shr_cast_reg_1289;
assign data_points_in_address = data_points_in_addr_reg_1066;
assign data_points_in_dataout = ap_const_lv32_0;
assign data_points_in_req_din = ap_const_logic_0;
assign data_points_in_size = ap_const_lv32_C;
assign distortion_out = total_distortion_reg_547;
assign exitcond1_fu_1016_p2 = (indvar1_reg_571 == tmp_14_add_i32_shr_reg_1284? 1'b1: 1'b0);
assign exitcond2_fu_670_p2 = (indvar2_phi_fu_528_p4 == ap_const_lv4_8? 1'b1: 1'b0);
assign exitcond7_fu_693_p2 = (i1_reg_536 == ap_const_lv3_4? 1'b1: 1'b0);
assign exitcond9_fu_587_p2 = (i_reg_477 == ap_const_lv9_100? 1'b1: 1'b0);
assign exitcond_fu_631_p2 = (indvar_phi_fu_516_p4 == ap_const_lv4_C? 1'b1: 1'b0);
assign grp_fu_898_ce = ap_const_logic_1;
assign grp_fu_898_p0 = centre_buffer_0_wgtCent_value_q0;
assign grp_fu_898_p1 = p_s_fu_891_p3;
assign grp_fu_905_ce = ap_const_logic_1;
assign grp_fu_905_p0 = centre_buffer_1_wgtCent_value_q0;
assign grp_fu_905_p1 = p_s_fu_891_p3;
assign grp_fu_918_ce = ap_const_logic_1;
assign grp_fu_918_p0 = reg_583;
assign grp_fu_918_p1 = p_s_reg_1262;
assign i1_cast8_fu_705_p1 = $unsigned(i1_reg_536);
assign i5_cast6_fu_859_p1 = $unsigned(i5_phi_fu_564_p4);
assign i_1_fu_593_p2 = (i_reg_477 + ap_const_lv9_1);
assign i_2_fu_853_p2 = (i5_phi_fu_564_p4 + ap_const_lv9_1);
assign i_3_fu_699_p2 = (i1_reg_536 + ap_const_lv3_1);
assign i_buffer_d0 = kernel_info_in_addr_read_reg_1119;
assign indvar_next1_fu_1021_p2 = (indvar1_reg_571 + ap_const_lv30_1);
assign indvar_next2_fu_676_p2 = (indvar2_phi_fu_528_p4 + ap_const_lv4_1);
assign indvar_next_fu_637_p2 = (indvar_phi_fu_516_p4 + ap_const_lv4_1);
assign isIter0_fu_643_p2 = (indvar_phi_fu_516_p4 == ap_const_lv4_0? 1'b1: 1'b0);
assign isIter1_fu_682_p2 = (indvar2_phi_fu_528_p4 == ap_const_lv4_0? 1'b1: 1'b0);
assign isIter_fu_1032_p2 = (indvar1_reg_571 == ap_const_lv30_0? 1'b1: 1'b0);
assign kernel_info_in_address = kernel_info_in_addr_reg_1100;
assign kernel_info_in_dataout = ap_const_lv32_0;
assign kernel_info_in_req_din = ap_const_logic_0;
assign kernel_info_in_size = ap_const_lv32_8;
assign lim_fu_608_p2 = n << ap_const_lv32_1;
assign p_buffer_d0 = data_points_in_addr_read_reg_1090;
assign p_s_fu_891_p3 = ((tmp_11_fu_886_p2)? ap_const_lv32_1: centre_buffer_count_load_reg_1236);
assign p_shl1_cast_fu_876_p1 = $unsigned(p_shl1_fu_868_p3);
assign p_shl1_fu_868_p3 = {{i5_phi_fu_564_p4}, {ap_const_lv2_0}};
assign p_shl2_cast_fu_971_p1 = $unsigned(p_shl2_fu_964_p3);
assign p_shl2_fu_964_p3 = {{k_V}, {ap_const_lv4_0}};
assign p_shl3_cast_fu_982_p1 = $unsigned(p_shl3_fu_975_p3);
assign p_shl3_fu_975_p3 = {{k_V}, {ap_const_lv2_0}};
assign p_shl_cast_fu_732_p1 = $unsigned(p_shl_fu_724_p3);
assign p_shl_fu_724_p3 = {{tmp_21_fu_709_p1}, {ap_const_lv2_0}};
assign tmp_10_fu_880_p2 = (p_shl1_cast_fu_876_p1 - i5_cast6_fu_859_p1);
assign tmp_11_fu_886_p2 = (centre_buffer_count_load_reg_1236 == ap_const_lv32_0? 1'b1: 1'b0);
assign tmp_13_fu_930_p0 = $signed(ap_reg_ppstg_tmp_10_reg_1225_pp4_it17);
assign tmp_13_fu_930_p1 = $unsigned(tmp_13_fu_930_p0);
assign tmp_14_add_i32_shr_cast_fu_1012_p0 = $signed(tmp_9_fu_998_p4);
assign tmp_14_add_i32_shr_cast_fu_1012_p1 = $unsigned(tmp_14_add_i32_shr_cast_fu_1012_p0);
assign tmp_14_add_i32_shr_fu_1008_p1 = $signed(tmp_9_fu_998_p4);
assign tmp_14_add_i_fu_992_p2 = (tmp_5_fu_986_p2 + ap_const_lv13_F);
assign tmp_14_cast4_fu_924_p1 = $signed(ap_reg_ppstg_tmp_10_reg_1225_pp4_it17);
assign tmp_14_fu_649_p1 = $unsigned(ap_reg_ppstg_indvar_reg_512_pp1_it6);
assign tmp_15_fu_1027_p1 = $unsigned(indvar1_reg_571);
assign tmp_17_fu_719_p1 = $unsigned(tmp_22_fu_713_p2);
assign tmp_18_fu_773_p3 = {{tmp_21_reg_1133}, {ap_const_lv1_1}};
assign tmp_19_fu_780_p1 = $unsigned(tmp_18_fu_773_p3);
assign tmp_20_fu_736_p2 = (p_shl_cast_fu_732_p1 - i1_cast8_fu_705_p1);
assign tmp_21_fu_709_p1 = i1_reg_536[1:0];
assign tmp_22_fu_713_p2 = i1_reg_536 << ap_const_lv3_1;
assign tmp_23_fu_746_p0 = $signed(tmp_20_fu_736_p2);
assign tmp_23_fu_746_p1 = $unsigned(tmp_23_fu_746_p0);
assign tmp_24_1_fu_935_p0 = $signed(ap_reg_ppstg_tmp_10_reg_1225_pp4_it17);
assign tmp_24_1_fu_935_p2 = (tmp_24_1_fu_935_p0 + ap_const_lv13_1);
assign tmp_24_2_fu_950_p2 = (tmp_14_cast4_reg_1279 + ap_const_lv13_2);
assign tmp_24_fu_799_p1 = $unsigned(i_buffer_q0);
assign tmp_25_1_fu_945_p0 = $signed(tmp_24_1_fu_935_p2);
assign tmp_25_1_fu_945_p1 = $unsigned(tmp_25_1_fu_945_p0);
assign tmp_25_2_fu_959_p0 = $signed(tmp_24_2_fu_950_p2);
assign tmp_25_2_fu_959_p1 = $unsigned(tmp_25_2_fu_959_p0);
assign tmp_25_fu_766_p1 = $unsigned(i1_reg_536);
assign tmp_26_fu_821_p2 = (centre_buffer_count_q0 + ap_const_lv32_1);
assign tmp_27_fu_828_p2 = (centre_buffer_sum_sq_q0 + i_buffer_q0);
assign tmp_28_1_fu_751_p2 = (tmp_20_fu_736_p2 + ap_const_lv5_1);
assign tmp_28_2_fu_785_p2 = (tmp_20_reg_1143 + ap_const_lv5_2);
assign tmp_28_fu_807_p2 = (p_buffer_q0 + centre_buffer_0_wgtCent_value_q0);
assign tmp_29_1_fu_761_p0 = $signed(tmp_28_1_fu_751_p2);
assign tmp_29_1_fu_761_p1 = $unsigned(tmp_29_1_fu_761_p0);
assign tmp_29_2_fu_794_p0 = $signed(tmp_28_2_fu_785_p2);
assign tmp_29_2_fu_794_p1 = $unsigned(tmp_29_2_fu_794_p0);
assign tmp_29_fu_688_p1 = $unsigned(ap_reg_ppstg_indvar2_reg_524_pp2_it6);
assign tmp_2_fu_599_p1 = $unsigned(i_reg_477);
assign tmp_35_1_fu_814_p2 = (p_buffer_q1 + centre_buffer_1_wgtCent_value_q0);
assign tmp_35_2_fu_835_p2 = (p_buffer_q1 + reg_583);
assign tmp_3_fu_613_p2 = (b_reg_500 > lim_reg_1058? 1'b1: 1'b0);
assign tmp_4_fu_618_p1 = $unsigned(b2_reg_488);
assign tmp_5_fu_986_p2 = (p_shl2_cast_fu_971_p1 - p_shl3_cast_fu_982_p1);
assign tmp_6_fu_863_p1 = $unsigned(i5_phi_fu_564_p4);
assign tmp_7_fu_660_p1 = $unsigned(b_reg_500);
assign tmp_9_cast_cast_fu_628_p1 = $unsigned(k_V);
assign tmp_9_fu_998_p4 = {{tmp_14_add_i_fu_992_p2[ap_const_lv32_C : ap_const_lv32_2]}};
assign tmp_s_fu_848_p2 = (i5_phi_fu_564_p4 > tmp_9_cast_cast_reg_1072? 1'b1: 1'b0);
assign total_distortion_1_fu_912_p2 = (centre_buffer_sum_sq_q0 + total_distortion_phi_fu_552_p4);
always @ (posedge ap_clk)
begin
    lim_reg_1058[0] <= 1'b0;
    tmp_9_cast_cast_reg_1072[8] <= 1'b0;
    tmp_24_reg_1183[63:32] <= 32'b00000000000000000000000000000000;
    tmp_6_reg_1212[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    tmp_14_add_i32_shr_cast_reg_1289[31:30] <= 2'b00;
end



endmodule //combiner_top

