// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdummy_hwhb_generator.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDummy_hwhb_generator_CfgInitialize(XDummy_hwhb_generator *InstancePtr, XDummy_hwhb_generator_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_a_BaseAddress = ConfigPtr->Bus_a_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDummy_hwhb_generator_Start(XDummy_hwhb_generator *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_AP_CTRL) & 0x80;
    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDummy_hwhb_generator_IsDone(XDummy_hwhb_generator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDummy_hwhb_generator_IsIdle(XDummy_hwhb_generator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDummy_hwhb_generator_IsReady(XDummy_hwhb_generator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDummy_hwhb_generator_EnableAutoRestart(XDummy_hwhb_generator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_AP_CTRL, 0x80);
}

void XDummy_hwhb_generator_DisableAutoRestart(XDummy_hwhb_generator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_AP_CTRL, 0);
}

void XDummy_hwhb_generator_SetDebug1(XDummy_hwhb_generator *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_DEBUG1_DATA, Data);
}

u32 XDummy_hwhb_generator_GetDebug1(XDummy_hwhb_generator *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_DEBUG1_DATA);
    return Data;
}

void XDummy_hwhb_generator_InterruptGlobalEnable(XDummy_hwhb_generator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_GIE, 1);
}

void XDummy_hwhb_generator_InterruptGlobalDisable(XDummy_hwhb_generator *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_GIE, 0);
}

void XDummy_hwhb_generator_InterruptEnable(XDummy_hwhb_generator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_IER);
    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_IER, Register | Mask);
}

void XDummy_hwhb_generator_InterruptDisable(XDummy_hwhb_generator *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_IER);
    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_IER, Register & (~Mask));
}

void XDummy_hwhb_generator_InterruptClear(XDummy_hwhb_generator *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDummy_hwhb_generator_WriteReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_ISR, Mask);
}

u32 XDummy_hwhb_generator_InterruptGetEnabled(XDummy_hwhb_generator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_IER);
}

u32 XDummy_hwhb_generator_InterruptGetStatus(XDummy_hwhb_generator *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDummy_hwhb_generator_ReadReg(InstancePtr->Bus_a_BaseAddress, XDUMMY_HWHB_GENERATOR_BUS_A_ADDR_ISR);
}

