#!/bin/bash

rm ../output_bitstream/k_means_system.bit 
rm ../output_bitstream/k_means_system.bit.bin

cd ./kernel/HLS/
vivado_hls kernel/kernel/auto_script.tcl
rm *.log
echo "--------------------------------------------"
echo "Built the kernel core"
echo "--------------------------------------------" 
cd ../../

cd ./combiner/HLS/
vivado_hls combiner/combiner/auto_script.tcl
rm *.log
echo "--------------------------------------------"
echo "Built the combiner core"
echo "--------------------------------------------"
cd ../../

cd RTL/k_means_zynq/
make

echo "--------------------------------------------"
echo "Built the entire system"
echo "--------------------------------------------" 



