// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xcombiner_top.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XCombiner_top_CfgInitialize(XCombiner_top *InstancePtr, XCombiner_top_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Config_bus_BaseAddress = ConfigPtr->Config_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XCombiner_top_Start(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_AP_CTRL) & 0x80;
    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XCombiner_top_IsDone(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XCombiner_top_IsIdle(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XCombiner_top_IsReady(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XCombiner_top_EnableAutoRestart(XCombiner_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_AP_CTRL, 0x80);
}

void XCombiner_top_DisableAutoRestart(XCombiner_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_AP_CTRL, 0);
}

void XCombiner_top_SetData_points_in_addr(XCombiner_top *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_DATA_POINTS_IN_ADDR_DATA, Data);
}

u32 XCombiner_top_GetData_points_in_addr(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_DATA_POINTS_IN_ADDR_DATA);
    return Data;
}

void XCombiner_top_SetKernel_info_in_addr(XCombiner_top *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_KERNEL_INFO_IN_ADDR_DATA, Data);
}

u32 XCombiner_top_GetKernel_info_in_addr(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_KERNEL_INFO_IN_ADDR_DATA);
    return Data;
}

void XCombiner_top_SetCentres_out_addr(XCombiner_top *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_CENTRES_OUT_ADDR_DATA, Data);
}

u32 XCombiner_top_GetCentres_out_addr(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_CENTRES_OUT_ADDR_DATA);
    return Data;
}

u32 XCombiner_top_GetDistortion_out(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_DISTORTION_OUT_DATA);
    return Data;
}

void XCombiner_top_SetN(XCombiner_top *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_N_DATA, Data);
}

u32 XCombiner_top_GetN(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_N_DATA);
    return Data;
}

void XCombiner_top_SetK(XCombiner_top *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_K_DATA, Data);
}

u32 XCombiner_top_GetK(XCombiner_top *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_K_DATA);
    return Data;
}

void XCombiner_top_InterruptGlobalEnable(XCombiner_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_GIE, 1);
}

void XCombiner_top_InterruptGlobalDisable(XCombiner_top *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_GIE, 0);
}

void XCombiner_top_InterruptEnable(XCombiner_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_IER);
    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_IER, Register | Mask);
}

void XCombiner_top_InterruptDisable(XCombiner_top *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_IER);
    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_IER, Register & (~Mask));
}

void XCombiner_top_InterruptClear(XCombiner_top *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XCombiner_top_WriteReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_ISR, Mask);
}

u32 XCombiner_top_InterruptGetEnabled(XCombiner_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_IER);
}

u32 XCombiner_top_InterruptGetStatus(XCombiner_top *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XCombiner_top_ReadReg(InstancePtr->Config_bus_BaseAddress, XCOMBINER_TOP_CONFIG_BUS_ADDR_ISR);
}

