// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.3
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef HHB_QUERY_H
#define HHB_QUERY_H

#ifdef __cplusplus
extern "C" {
#endif

#define HHBQUERY_ADDR     0x43C00000

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "hhb_query_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_a_BaseAddress;
} HHB_query_Config;
#endif

typedef struct {
    u32 Bus_a_BaseAddress;
    u32 IsReady;
} HHB_query;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define HHB_query_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define HHB_query_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define HHB_query_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define HHB_query_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int HHB_query_Initialize(HHB_query *InstancePtr, u16 DeviceId);
HHB_query_Config* HHB_query_LookupConfig(u16 DeviceId);
int HHB_query_CfgInitialize(HHB_query *InstancePtr, XExample_Config *ConfigPtr);
#else
int HHB_query_Initialize(HHB_query *InstancePtr, const char* InstanceName);
int HHB_query_Release(HHB_query *InstancePtr);
#endif


HHB_query setup_hhbquery();
void HHB_query_Start(HHB_query *InstancePtr);
u32 HHB_query_IsDone(HHB_query *InstancePtr);
u32 HHB_query_IsIdle(HHB_query *InstancePtr);
u32 HHB_query_IsReady(HHB_query *InstancePtr);
void HHB_query_EnableAutoRestart(HHB_query *InstancePtr);
void HHB_query_DisableAutoRestart(HHB_query *InstancePtr);

void HHB_query_SetHeartbeat_record_phys_addr(HHB_query *InstancePtr, u32 Data);
u32 HHB_query_GetHeartbeat_record_phys_addr(HHB_query *InstancePtr);
u32 HHB_query_GetCurrent_heartbeat(HHB_query *InstancePtr);
u32 HHB_query_GetStatus(HHB_query *InstancePtr);

void HHB_query_InterruptGlobalEnable(HHB_query *InstancePtr);
void HHB_query_InterruptGlobalDisable(HHB_query *InstancePtr);
void HHB_query_InterruptEnable(HHB_query *InstancePtr, u32 Mask);
void HHB_query_InterruptDisable(HHB_query *InstancePtr, u32 Mask);
void HHB_query_InterruptClear(HHB_query *InstancePtr, u32 Mask);
u32 HHB_query_InterruptGetEnabled(HHB_query *InstancePtr);
u32 HHB_query_InterruptGetStatus(HHB_query *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
