// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module store_output_points_buffer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        offset,
        address,
        bus_r_req_din,
        bus_r_req_full_n,
        bus_r_req_write,
        bus_r_rsp_empty_n,
        bus_r_rsp_read,
        bus_r_address,
        bus_r_datain,
        bus_r_dataout,
        bus_r_size
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] offset;
input  [31:0] address;
output   bus_r_req_din;
input   bus_r_req_full_n;
output   bus_r_req_write;
input   bus_r_rsp_empty_n;
output   bus_r_rsp_read;
output  [31:0] bus_r_address;
input  [31:0] bus_r_datain;
output  [31:0] bus_r_dataout;
output  [31:0] bus_r_size;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bus_r_req_din;
reg bus_r_req_write;
reg   [2:0] ap_CS_fsm = 3'b000;
reg   [5:0] indvar_reg_154;
wire   [0:0] exitcond1_fu_166_p2;
reg   [0:0] exitcond1_reg_303;
wire   [4:0] i_1_fu_172_p2;
reg   [4:0] i_1_reg_307;
wire   [6:0] tmp_4_fu_198_p2;
reg   [6:0] tmp_4_reg_312;
reg   [31:0] bus_addr_reg_317;
wire   [0:0] exitcond2_fu_266_p2;
reg   [0:0] exitcond2_reg_322;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond2_reg_322_pp1_it1;
reg    ap_sig_bdd_71;
reg    ap_reg_ppiten_pp1_it2 = 1'b0;
wire   [5:0] indvar_next_fu_272_p2;
wire   [0:0] isIter0_fu_283_p2;
reg   [0:0] isIter0_reg_336;
reg   [0:0] ap_reg_ppstg_isIter0_reg_336_pp1_it1;
wire   [0:0] int_buffer_q1;
reg   [0:0] int_buffer_load_reg_340;
reg   [5:0] int_buffer_address0;
reg    int_buffer_ce0;
reg    int_buffer_we0;
wire   [0:0] int_buffer_d0;
reg   [5:0] int_buffer_address1;
reg    int_buffer_ce1;
reg    int_buffer_we1;
wire   [0:0] int_buffer_d1;
reg   [4:0] i_reg_143;
wire   [63:0] tmp_6_fu_208_p1;
wire   [63:0] tmp_6_1_fu_223_p1;
wire   [63:0] tmp_6_2_fu_237_p1;
wire   [63:0] tmp_3_fu_278_p1;
wire   [63:0] tmp_1_cast_fu_256_p1;
wire   [3:0] tmp_5_fu_182_p1;
wire   [5:0] p_shl_fu_186_p3;
wire   [6:0] p_shl_cast_fu_194_p1;
wire   [6:0] i_cast2_fu_178_p1;
wire   [31:0] tmp_6_fu_208_p0;
wire   [6:0] tmp_5_1_fu_213_p2;
wire   [31:0] tmp_6_1_fu_223_p0;
wire   [6:0] tmp_5_2_fu_228_p2;
wire   [31:0] tmp_6_2_fu_237_p0;
wire   [31:0] tmp_fu_242_p2;
wire   [29:0] tmp_1_fu_246_p4;
reg   [2:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 3'b000;
parameter    ap_ST_st2_fsm_1 = 3'b1;
parameter    ap_ST_st3_fsm_2 = 3'b10;
parameter    ap_ST_st4_fsm_3 = 3'b11;
parameter    ap_ST_pp1_stg0_fsm_4 = 3'b100;
parameter    ap_ST_st8_fsm_5 = 3'b101;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv5_10 = 5'b10000;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv7_2 = 7'b10;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv6_30 = 6'b110000;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_true = 1'b1;


store_output_points_buffer_int_buffer #(
    .DataWidth( 1 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
int_buffer_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( int_buffer_address0 ),
    .ce0( int_buffer_ce0 ),
    .we0( int_buffer_we0 ),
    .d0( int_buffer_d0 ),
    .address1( int_buffer_address1 ),
    .ce1( int_buffer_ce1 ),
    .we1( int_buffer_we1 ),
    .d1( int_buffer_d1 ),
    .q1( int_buffer_q1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp1_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_lv1_0 == exitcond2_fu_266_p2))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp1_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & (ap_const_lv1_0 == exitcond2_fu_266_p2))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if (((ap_ST_st4_fsm_3 == ap_CS_fsm) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_lv1_0 == exitcond2_fu_266_p2)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp1_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp1_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
    end else begin
        if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)))) begin
            ap_reg_ppiten_pp1_it2 <= ap_reg_ppiten_pp1_it1;
        end else if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
            ap_reg_ppiten_pp1_it2 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (exitcond1_reg_303 == ap_const_lv1_0))) begin
        i_reg_143 <= i_1_reg_307;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        i_reg_143 <= ap_const_lv5_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        indvar_reg_154 <= ap_const_lv6_0;
    end else if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & (ap_const_lv1_0 == exitcond2_fu_266_p2))) begin
        indvar_reg_154 <= indvar_next_fu_272_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)))) begin
        ap_reg_ppstg_exitcond2_reg_322_pp1_it1 <= exitcond2_reg_322;
        ap_reg_ppstg_isIter0_reg_336_pp1_it1 <= isIter0_reg_336;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        bus_addr_reg_317[0] <= tmp_1_cast_fu_256_p1[0];
bus_addr_reg_317[1] <= tmp_1_cast_fu_256_p1[1];
bus_addr_reg_317[2] <= tmp_1_cast_fu_256_p1[2];
bus_addr_reg_317[3] <= tmp_1_cast_fu_256_p1[3];
bus_addr_reg_317[4] <= tmp_1_cast_fu_256_p1[4];
bus_addr_reg_317[5] <= tmp_1_cast_fu_256_p1[5];
bus_addr_reg_317[6] <= tmp_1_cast_fu_256_p1[6];
bus_addr_reg_317[7] <= tmp_1_cast_fu_256_p1[7];
bus_addr_reg_317[8] <= tmp_1_cast_fu_256_p1[8];
bus_addr_reg_317[9] <= tmp_1_cast_fu_256_p1[9];
bus_addr_reg_317[10] <= tmp_1_cast_fu_256_p1[10];
bus_addr_reg_317[11] <= tmp_1_cast_fu_256_p1[11];
bus_addr_reg_317[12] <= tmp_1_cast_fu_256_p1[12];
bus_addr_reg_317[13] <= tmp_1_cast_fu_256_p1[13];
bus_addr_reg_317[14] <= tmp_1_cast_fu_256_p1[14];
bus_addr_reg_317[15] <= tmp_1_cast_fu_256_p1[15];
bus_addr_reg_317[16] <= tmp_1_cast_fu_256_p1[16];
bus_addr_reg_317[17] <= tmp_1_cast_fu_256_p1[17];
bus_addr_reg_317[18] <= tmp_1_cast_fu_256_p1[18];
bus_addr_reg_317[19] <= tmp_1_cast_fu_256_p1[19];
bus_addr_reg_317[20] <= tmp_1_cast_fu_256_p1[20];
bus_addr_reg_317[21] <= tmp_1_cast_fu_256_p1[21];
bus_addr_reg_317[22] <= tmp_1_cast_fu_256_p1[22];
bus_addr_reg_317[23] <= tmp_1_cast_fu_256_p1[23];
bus_addr_reg_317[24] <= tmp_1_cast_fu_256_p1[24];
bus_addr_reg_317[25] <= tmp_1_cast_fu_256_p1[25];
bus_addr_reg_317[26] <= tmp_1_cast_fu_256_p1[26];
bus_addr_reg_317[27] <= tmp_1_cast_fu_256_p1[27];
bus_addr_reg_317[28] <= tmp_1_cast_fu_256_p1[28];
bus_addr_reg_317[29] <= tmp_1_cast_fu_256_p1[29];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        exitcond1_reg_303 <= exitcond1_fu_166_p2;
        i_1_reg_307 <= i_1_fu_172_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)))) begin
        exitcond2_reg_322 <= exitcond2_fu_266_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & (ap_const_lv1_0 == exitcond2_reg_322))) begin
        int_buffer_load_reg_340 <= int_buffer_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & (ap_const_lv1_0 == exitcond2_fu_266_p2))) begin
        isIter0_reg_336 <= isIter0_fu_283_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond1_fu_166_p2 == ap_const_lv1_0))) begin
        tmp_4_reg_312 <= tmp_4_fu_198_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | (ap_ST_st8_fsm_5 == ap_CS_fsm))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st8_fsm_5 == ap_CS_fsm)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// bus_r_req_din assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond2_reg_322_pp1_it1 or ap_sig_bdd_71 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_isIter0_reg_336_pp1_it1)
begin
    if ((((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_322_pp1_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_lv1_0 == ap_reg_ppstg_isIter0_reg_336_pp1_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_322_pp1_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2))))) begin
        bus_r_req_din = ap_const_logic_1;
    end else begin
        bus_r_req_din = ap_const_logic_0;
    end
end

/// bus_r_req_write assign process. ///
always @ (ap_CS_fsm or ap_reg_ppstg_exitcond2_reg_322_pp1_it1 or ap_sig_bdd_71 or ap_reg_ppiten_pp1_it2 or ap_reg_ppstg_isIter0_reg_336_pp1_it1)
begin
    if ((((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_322_pp1_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_lv1_0 == ap_reg_ppstg_isIter0_reg_336_pp1_it1)) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_322_pp1_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2))))) begin
        bus_r_req_write = ap_const_logic_1;
    end else begin
        bus_r_req_write = ap_const_logic_0;
    end
end

/// int_buffer_address0 assign process. ///
always @ (ap_CS_fsm or tmp_6_fu_208_p1 or tmp_6_2_fu_237_p1)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        int_buffer_address0 = tmp_6_2_fu_237_p1;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        int_buffer_address0 = tmp_6_fu_208_p1;
    end else begin
        int_buffer_address0 = 'bx;
    end
end

/// int_buffer_address1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp1_it0 or tmp_6_1_fu_223_p1 or tmp_3_fu_278_p1)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        int_buffer_address1 = tmp_6_1_fu_223_p1;
    end else if (((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0))) begin
        int_buffer_address1 = tmp_3_fu_278_p1;
    end else begin
        int_buffer_address1 = 'bx;
    end
end

/// int_buffer_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | (ap_ST_st3_fsm_2 == ap_CS_fsm))) begin
        int_buffer_ce0 = ap_const_logic_1;
    end else begin
        int_buffer_ce0 = ap_const_logic_0;
    end
end

/// int_buffer_ce1 assign process. ///
always @ (ap_CS_fsm or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_71 or ap_reg_ppiten_pp1_it2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) | ((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2))))) begin
        int_buffer_ce1 = ap_const_logic_1;
    end else begin
        int_buffer_ce1 = ap_const_logic_0;
    end
end

/// int_buffer_we0 assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_166_p2 or exitcond1_reg_303)
begin
    if ((((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond1_fu_166_p2 == ap_const_lv1_0)) | ((ap_ST_st3_fsm_2 == ap_CS_fsm) & (exitcond1_reg_303 == ap_const_lv1_0)))) begin
        int_buffer_we0 = ap_const_logic_1;
    end else begin
        int_buffer_we0 = ap_const_logic_0;
    end
end

/// int_buffer_we1 assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_166_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond1_fu_166_p2 == ap_const_lv1_0))) begin
        int_buffer_we1 = ap_const_logic_1;
    end else begin
        int_buffer_we1 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond1_fu_166_p2 or exitcond2_fu_266_p2 or ap_reg_ppiten_pp1_it0 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_71 or ap_reg_ppiten_pp1_it2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if ((exitcond1_fu_166_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        ap_ST_st3_fsm_2 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
        ap_ST_st4_fsm_3 : 
            ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
        ap_ST_pp1_stg0_fsm_4 : 
            if ((~((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_lv1_0 == exitcond2_fu_266_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if ((((ap_ST_pp1_stg0_fsm_4 == ap_CS_fsm) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)) | ((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~(ap_sig_bdd_71 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it2)) & ~(ap_const_lv1_0 == exitcond2_fu_266_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))) begin
                ap_NS_fsm = ap_ST_st8_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        ap_ST_st8_fsm_5 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end

/// ap_sig_bdd_71 assign process. ///
always @ (bus_r_req_full_n or ap_reg_ppstg_exitcond2_reg_322_pp1_it1)
begin
    ap_sig_bdd_71 = ((bus_r_req_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond2_reg_322_pp1_it1));
end
assign bus_r_address = bus_addr_reg_317;
assign bus_r_dataout = $unsigned(int_buffer_load_reg_340);
assign bus_r_rsp_read = ap_const_logic_0;
assign bus_r_size = ap_const_lv32_30;
assign exitcond1_fu_166_p2 = (i_reg_143 == ap_const_lv5_10? 1'b1: 1'b0);
assign exitcond2_fu_266_p2 = (indvar_reg_154 == ap_const_lv6_30? 1'b1: 1'b0);
assign i_1_fu_172_p2 = (i_reg_143 + ap_const_lv5_1);
assign i_cast2_fu_178_p1 = $unsigned(i_reg_143);
assign indvar_next_fu_272_p2 = (indvar_reg_154 + ap_const_lv6_1);
assign int_buffer_d0 = ap_const_lv1_0;
assign int_buffer_d1 = ap_const_lv1_0;
assign isIter0_fu_283_p2 = (indvar_reg_154 == ap_const_lv6_0? 1'b1: 1'b0);
assign p_shl_cast_fu_194_p1 = $unsigned(p_shl_fu_186_p3);
assign p_shl_fu_186_p3 = {{tmp_5_fu_182_p1}, {ap_const_lv2_0}};
assign tmp_1_cast_fu_256_p1 = $unsigned(tmp_1_fu_246_p4);
assign tmp_1_fu_246_p4 = {{tmp_fu_242_p2[ap_const_lv32_1F : ap_const_lv32_2]}};
assign tmp_3_fu_278_p1 = $unsigned(indvar_reg_154);
assign tmp_4_fu_198_p2 = (p_shl_cast_fu_194_p1 - i_cast2_fu_178_p1);
assign tmp_5_1_fu_213_p2 = (tmp_4_fu_198_p2 + ap_const_lv7_1);
assign tmp_5_2_fu_228_p2 = (tmp_4_reg_312 + ap_const_lv7_2);
assign tmp_5_fu_182_p1 = i_reg_143[3:0];
assign tmp_6_1_fu_223_p0 = $signed(tmp_5_1_fu_213_p2);
assign tmp_6_1_fu_223_p1 = $unsigned(tmp_6_1_fu_223_p0);
assign tmp_6_2_fu_237_p0 = $signed(tmp_5_2_fu_228_p2);
assign tmp_6_2_fu_237_p1 = $unsigned(tmp_6_2_fu_237_p0);
assign tmp_6_fu_208_p0 = $signed(tmp_4_fu_198_p2);
assign tmp_6_fu_208_p1 = $unsigned(tmp_6_fu_208_p0);
assign tmp_fu_242_p2 = (address + offset);
always @ (posedge ap_clk)
begin
    bus_addr_reg_317[31:30] <= 2'b00;
end



endmodule //store_output_points_buffer

